// Biblioteca de ejercicios de Forus (contenido propio en español).
// Imágenes: free-exercise-db (dominio público, Unlicense) → campo `img`.
// Formato: [id, img, nombre, patrón, equipo, principales, secundarios, claves, errores, unilateral]
// patrón: sentadilla | bisagra | zancada | empuje_h | empuje_v | tiron_h | tiron_v | aislamiento | core | acarreo
// equipo: barra | mancuerna | polea | maquina | smith | corporal | kettlebell | ez | banda | otro

export const EXERCISES = [
  // ── Piernas: sentadilla y prensa ──
  ['sentadilla-barra', 'Barbell_Squat', 'Sentadilla con barra', 'sentadilla', 'barra', 'cuadriceps,gluteos', 'aductores,lumbar', 'Barra sobre trapecios, pies al ancho de hombros | Baja controlado hasta que la cadera pase la rodilla | Empuja el piso con todo el pie', 'Rodillas hacia adentro | Talones que se despegan'],
  ['sentadilla-frontal', 'Front_Barbell_Squat', 'Sentadilla frontal', 'sentadilla', 'barra', 'cuadriceps', 'gluteos,abdomen', 'Barra sobre deltoides, codos altos | Torso lo más vertical posible', 'Codos que caen y la barra rueda'],
  ['sentadilla-caja', 'Box_Squat', 'Sentadilla a cajón', 'sentadilla', 'barra', 'cuadriceps,gluteos', 'isquios', 'Siéntate atrás hasta tocar el cajón | Sube sin rebotar', 'Dejarse caer sobre el cajón'],
  ['sentadilla-goblet', 'Goblet_Squat', 'Sentadilla goblet', 'sentadilla', 'kettlebell', 'cuadriceps,gluteos', 'abdomen', 'Pesa pegada al pecho | Codos por dentro de las rodillas al bajar', 'Encorvar la espalda'],
  ['sentadilla-mancuernas', 'Dumbbell_Squat', 'Sentadilla con mancuernas', 'sentadilla', 'mancuerna', 'cuadriceps,gluteos', '', 'Mancuernas a los costados | Pecho arriba durante todo el recorrido', 'Recorrido corto'],
  ['sentadilla-smith', 'Smith_Machine_Squat', 'Sentadilla en Smith', 'sentadilla', 'smith', 'cuadriceps,gluteos', '', 'Pies un poco adelante de la barra | Baja controlado', 'Bloquear las rodillas de golpe arriba'],
  ['sentadilla-hack', 'Hack_Squat', 'Sentadilla hack (máquina)', 'sentadilla', 'maquina', 'cuadriceps', 'gluteos', 'Espalda pegada al respaldo | Baja profundo sin despegar talones', 'Despegar la cadera del respaldo'],
  ['sentadilla-sumo-mancuerna', 'Plie_Dumbbell_Squat', 'Sentadilla sumo con mancuerna', 'sentadilla', 'mancuerna', 'aductores,gluteos', 'cuadriceps', 'Pies abiertos, puntas hacia afuera | Rodillas siguen la línea de los pies', 'Rodillas hacia adentro'],
  ['sentadilla-peso-corporal', 'Bodyweight_Squat', 'Sentadilla con peso corporal', 'sentadilla', 'corporal', 'cuadriceps,gluteos', '', 'Brazos al frente para equilibrar | Baja lo más que puedas con buena técnica', 'Talones que se despegan'],
  ['sentadilla-sissy', 'Weighted_Sissy_Squat', 'Sentadilla sissy', 'sentadilla', 'corporal', 'cuadriceps', '', 'Rodillas adelante, cadera extendida | Recorrido controlado', 'Doblar la cadera'],
  ['sentadilla-pistol', 'Kettlebell_Pistol_Squat', 'Sentadilla a una pierna (pistol)', 'sentadilla', 'corporal', 'cuadriceps,gluteos', '', 'Pierna libre al frente | Baja lento con apoyo si lo necesitas', 'Rodilla que colapsa hacia adentro', true],
  ['prensa', 'Leg_Press', 'Prensa de piernas', 'sentadilla', 'maquina', 'cuadriceps,gluteos', 'aductores', 'Pies al centro de la plataforma | Baja hasta ~90° sin despegar la zona lumbar', 'Bloquear las rodillas arriba | Despegar la pelvis del asiento'],
  ['prensa-estrecha', 'Narrow_Stance_Leg_Press', 'Prensa con pies juntos', 'sentadilla', 'maquina', 'cuadriceps', '', 'Pies juntos en la parte baja | Recorrido completo', 'Talones que se levantan'],
  ['prensa-smith', 'Smith_Machine_Leg_Press', 'Prensa en Smith', 'sentadilla', 'smith', 'cuadriceps,gluteos', '', 'Espalda apoyada en el suelo | Empuja con todo el pie', 'Recorrido corto'],
  ['extension-cuadriceps', 'Leg_Extensions', 'Extensión de cuádriceps (sillón)', 'aislamiento', 'maquina', 'cuadriceps', '', 'Rodilla alineada con el eje de la máquina | Aprieta 1 s arriba', 'Balancear el cuerpo | Bajar sin control'],
  ['extension-cuadriceps-1', 'Single-Leg_Leg_Extension', 'Extensión de cuádriceps a una pierna', 'aislamiento', 'maquina', 'cuadriceps', '', 'Una pierna a la vez | Controla la bajada', 'Usar impulso', true],

  // ── Piernas: zancadas ──
  ['estocada-mancuernas', 'Dumbbell_Lunges', 'Estocadas con mancuernas', 'zancada', 'mancuerna', 'cuadriceps,gluteos', 'isquios', 'Paso largo, torso erguido | Rodilla de atrás casi toca el piso', 'Paso muy corto | Rodilla adelantada que colapsa', true],
  ['estocada-barra', 'Barbell_Lunge', 'Estocadas con barra', 'zancada', 'barra', 'cuadriceps,gluteos', '', 'Barra estable sobre trapecios | Baja vertical', 'Perder el equilibrio por paso estrecho', true],
  ['estocada-caminando', 'Barbell_Walking_Lunge', 'Estocadas caminando', 'zancada', 'barra', 'cuadriceps,gluteos', '', 'Avanza con pasos controlados | Empuja con el talón de adelante', 'Inclinar el torso en exceso', true],
  ['estocada-caminando-corporal', 'Bodyweight_Walking_Lunge', 'Estocadas caminando (peso corporal)', 'zancada', 'corporal', 'cuadriceps,gluteos', '', 'Pasos largos | Torso erguido', 'Rodilla que golpea el piso', true],
  ['estocada-atras', 'Dumbbell_Rear_Lunge', 'Estocada hacia atrás', 'zancada', 'mancuerna', 'gluteos,cuadriceps', '', 'Da el paso hacia atrás | Carga en la pierna de adelante', 'Empujar con la pierna de atrás', true],
  ['bulgara', 'Split_Squat_with_Dumbbells', 'Sentadilla búlgara', 'zancada', 'mancuerna', 'cuadriceps,gluteos', '', 'Pie de atrás sobre un banco | Baja vertical, rodilla sobre el pie', 'Pie delantero demasiado cerca del banco', true],
  ['split-smith', 'Smith_Single-Leg_Split_Squat', 'Split squat en Smith', 'zancada', 'smith', 'cuadriceps,gluteos', '', 'Posición de estocada fija | Sube y baja vertical', 'Recorrido corto', true],
  ['step-up', 'Dumbbell_Step_Ups', 'Subida al cajón con mancuernas', 'zancada', 'mancuerna', 'cuadriceps,gluteos', '', 'Sube empujando con la pierna de arriba | Baja controlado', 'Impulsarse con la pierna de abajo', true],

  // ── Piernas: bisagra y femorales ──
  ['peso-muerto', 'Barbell_Deadlift', 'Peso muerto', 'bisagra', 'barra', 'isquios,gluteos,lumbar', 'trapecio,cuadriceps,antebrazo', 'Barra sobre la mitad del pie | Espalda neutra, pecho arriba | Empuja el piso y extiende cadera y rodillas juntas', 'Redondear la espalda | Barra lejos del cuerpo'],
  ['peso-muerto-sumo', 'Sumo_Deadlift', 'Peso muerto sumo', 'bisagra', 'barra', 'gluteos,isquios,aductores', 'lumbar,cuadriceps', 'Pies abiertos, agarre por dentro de las piernas | Rodillas afuera', 'Cadera que sube antes que la barra'],
  ['peso-muerto-rumano', 'Romanian_Deadlift', 'Peso muerto rumano', 'bisagra', 'barra', 'isquios,gluteos', 'lumbar', 'Rodillas levemente flectadas | Lleva la cadera atrás con la barra pegada | Baja hasta sentir el estiramiento', 'Redondear la espalda | Convertirlo en sentadilla'],
  ['peso-muerto-rumano-mancuernas', 'Stiff-Legged_Dumbbell_Deadlift', 'Peso muerto rumano con mancuernas', 'bisagra', 'mancuerna', 'isquios,gluteos', 'lumbar', 'Mancuernas pegadas a las piernas | Cadera atrás', 'Doblar demasiado las rodillas'],
  ['peso-muerto-piernas-rigidas', 'Stiff-Legged_Barbell_Deadlift', 'Peso muerto piernas rígidas', 'bisagra', 'barra', 'isquios', 'gluteos,lumbar', 'Rodillas casi extendidas | Recorrido hasta donde mantengas la espalda neutra', 'Perder la curva lumbar'],
  ['peso-muerto-trap-bar', 'Trap_Bar_Deadlift', 'Peso muerto con barra hexagonal', 'bisagra', 'otro', 'cuadriceps,gluteos,isquios', 'trapecio,lumbar', 'Centrado dentro de la barra | Empuja el piso', 'Cadera muy alta al inicio'],
  ['peso-muerto-smith', 'Smith_Machine_Stiff-Legged_Deadlift', 'Peso muerto rumano en Smith', 'bisagra', 'smith', 'isquios,gluteos', '', 'Cadera atrás | Barra cerca del cuerpo', 'Redondear la espalda'],
  ['peso-muerto-una-pierna', 'Kettlebell_One-Legged_Deadlift', 'Peso muerto a una pierna', 'bisagra', 'kettlebell', 'isquios,gluteos', '', 'Pierna libre sigue la línea del torso | Cadera nivelada', 'Rotar la cadera', true],
  ['rack-pull', 'Rack_Pulls', 'Rack pull', 'bisagra', 'barra', 'lumbar,trapecio,gluteos', 'isquios', 'Barra sobre soportes a la altura de la rodilla | Extiende la cadera', 'Hiperextender la espalda arriba'],
  ['buenos-dias', 'Good_Morning', 'Buenos días (good morning)', 'bisagra', 'barra', 'isquios,lumbar', 'gluteos', 'Barra en la espalda | Inclina desde la cadera', 'Cargar demasiado peso'],
  ['hip-thrust', 'Barbell_Hip_Thrust', 'Hip thrust con barra', 'bisagra', 'barra', 'gluteos', 'isquios', 'Espalda alta en el banco, barra sobre la cadera | Sube hasta alinear tronco y muslos | Aprieta el glúteo 1 s', 'Hiperextender la zona lumbar'],
  ['puente-gluteo', 'Barbell_Glute_Bridge', 'Puente de glúteo con barra', 'bisagra', 'barra', 'gluteos', 'isquios', 'Espalda en el piso | Empuja con los talones', 'Arquear la espalda en vez de mover la cadera'],
  ['puente-gluteo-1', 'Single_Leg_Glute_Bridge', 'Puente de glúteo a una pierna', 'bisagra', 'corporal', 'gluteos', 'isquios', 'Una pierna extendida | Cadera nivelada', 'Rotar la pelvis', true],
  ['patada-gluteo-polea', 'One-Legged_Cable_Kickback', 'Patada de glúteo en polea', 'aislamiento', 'polea', 'gluteos', '', 'Tobillera en la polea baja | Lleva la pierna atrás sin arquear', 'Arquear la zona lumbar', true],
  ['pull-through', 'Pull_Through', 'Pull through en polea', 'bisagra', 'polea', 'gluteos,isquios', '', 'De espaldas a la polea | Cadera atrás y adelante', 'Tirar con los brazos'],
  ['hiperextension', 'Hyperextensions_Back_Extensions', 'Hiperextensiones (extensión lumbar)', 'bisagra', 'otro', 'lumbar,gluteos', 'isquios', 'Cadera apoyada en el cojín | Sube hasta alinear el cuerpo', 'Hiperextender arriba'],
  ['hiperextension-inversa', 'Reverse_Hyperextension', 'Hiperextensión inversa', 'bisagra', 'maquina', 'gluteos,isquios', 'lumbar', 'Torso apoyado | Eleva las piernas con los glúteos', 'Balanceo'],
  ['curl-femoral-tumbado', 'Lying_Leg_Curls', 'Curl femoral tumbado', 'aislamiento', 'maquina', 'isquios', 'gemelos', 'Cadera pegada al banco | Sube completo y baja lento', 'Levantar la cadera'],
  ['curl-femoral-sentado', 'Seated_Leg_Curl', 'Curl femoral sentado', 'aislamiento', 'maquina', 'isquios', '', 'Rodillas alineadas con el eje | Controla la vuelta', 'Recorrido corto'],
  ['curl-femoral-pie', 'Standing_Leg_Curl', 'Curl femoral de pie', 'aislamiento', 'maquina', 'isquios', '', 'Una pierna a la vez | Cadera quieta', 'Usar impulso', true],
  ['glute-ham', 'Glute_Ham_Raise', 'Glute ham raise', 'bisagra', 'maquina', 'isquios,gluteos', '', 'Rodillas en el cojín | Sube flectando las rodillas', 'Doblar la cadera'],
  ['nordico', 'Natural_Glute_Ham_Raise', 'Curl nórdico', 'aislamiento', 'corporal', 'isquios', '', 'Pies sujetos | Baja lo más lento posible', 'Doblar la cadera'],
  ['swing-kettlebell', 'One-Arm_Kettlebell_Swings', 'Swing con kettlebell', 'bisagra', 'kettlebell', 'gluteos,isquios', 'lumbar,delt_ant', 'Movimiento de cadera, no de brazos | Proyecta la pesa con un golpe de cadera', 'Hacer una sentadilla'],
  ['abductor-maquina', 'Thigh_Abductor', 'Abducción de cadera (máquina)', 'aislamiento', 'maquina', 'abductores,gluteos', '', 'Espalda apoyada | Abre controlado', 'Rebotar al cerrar'],
  ['aductor-maquina', 'Thigh_Adductor', 'Aducción de cadera (máquina)', 'aislamiento', 'maquina', 'aductores', '', 'Cierra controlado | Pausa al cerrar', 'Abrir más de lo cómodo con mucho peso'],
  ['caminata-banda', 'Monster_Walk', 'Caminata lateral con banda', 'aislamiento', 'banda', 'abductores,gluteos', '', 'Banda sobre las rodillas o tobillos | Pasos cortos con tensión constante', 'Juntar los pies'],

  // ── Pantorrillas ──
  ['gemelos-pie-maquina', 'Standing_Calf_Raises', 'Elevación de talones de pie (máquina)', 'aislamiento', 'maquina', 'gemelos', '', 'Recorrido completo | Pausa 1 s abajo y arriba', 'Rebotar'],
  ['gemelos-sentado', 'Seated_Calf_Raise', 'Elevación de talones sentado', 'aislamiento', 'maquina', 'gemelos', '', 'Rodillas bajo el cojín | Estira completo abajo', 'Recorrido corto'],
  ['gemelos-prensa', 'Calf_Press_On_The_Leg_Press_Machine', 'Gemelos en prensa', 'aislamiento', 'maquina', 'gemelos', '', 'Punta de los pies en el borde | Rodillas extendidas sin bloquear', 'Doblar las rodillas'],
  ['gemelos-smith', 'Smith_Machine_Calf_Raise', 'Elevación de talones en Smith', 'aislamiento', 'smith', 'gemelos', '', 'Punta de los pies sobre un disco | Recorrido completo', 'Rebotar'],
  ['gemelos-barra', 'Standing_Barbell_Calf_Raise', 'Elevación de talones con barra', 'aislamiento', 'barra', 'gemelos', '', 'Barra en la espalda | Sube lento', 'Perder el equilibrio'],
  ['gemelos-mancuerna', 'Standing_Dumbbell_Calf_Raise', 'Elevación de talones con mancuerna', 'aislamiento', 'mancuerna', 'gemelos', '', 'Apóyate en algo | Una pierna a la vez si es fácil', 'Recorrido corto', true],
  ['gemelos-burro', 'Donkey_Calf_Raises', 'Gemelos tipo burro', 'aislamiento', 'otro', 'gemelos', '', 'Torso inclinado | Estiramiento completo', 'Rebotar'],

  // ── Pecho ──
  ['press-banca', 'Barbell_Bench_Press_-_Medium_Grip', 'Press de banca', 'empuje_h', 'barra', 'pecho', 'triceps,delt_ant', 'Escápulas juntas y hacia abajo | Baja la barra a la parte baja del pecho | Pies firmes en el piso', 'Rebotar la barra en el pecho | Codos abiertos a 90°'],
  ['press-banca-inclinado', 'Barbell_Incline_Bench_Press_-_Medium_Grip', 'Press inclinado con barra', 'empuje_h', 'barra', 'pecho', 'delt_ant,triceps', 'Banco a 30–45° | Baja a la parte alta del pecho', 'Banco demasiado inclinado'],
  ['press-banca-declinado', 'Decline_Barbell_Bench_Press', 'Press declinado con barra', 'empuje_h', 'barra', 'pecho', 'triceps', 'Piernas sujetas | Baja a la parte baja del pecho', 'Bajar demasiado rápido'],
  ['press-banca-cerrado', 'Close-Grip_Barbell_Bench_Press', 'Press de banca agarre cerrado', 'empuje_h', 'barra', 'triceps', 'pecho,delt_ant', 'Manos al ancho de hombros | Codos pegados al cuerpo', 'Agarre demasiado cerrado (muñecas)'],
  ['press-banca-abierto', 'Wide-Grip_Barbell_Bench_Press', 'Press de banca agarre abierto', 'empuje_h', 'barra', 'pecho', 'delt_ant', 'Agarre más ancho que los hombros | Controla la bajada', 'Codos muy abiertos'],
  ['press-mancuernas', 'Dumbbell_Bench_Press', 'Press con mancuernas', 'empuje_h', 'mancuerna', 'pecho', 'triceps,delt_ant', 'Mancuernas a la altura del pecho | Sube juntándolas levemente', 'Bajar poco'],
  ['press-mancuernas-inclinado', 'Incline_Dumbbell_Press', 'Press inclinado con mancuernas', 'empuje_h', 'mancuerna', 'pecho', 'delt_ant,triceps', 'Banco a 30–45° | Codos a 45° del cuerpo', 'Arquear demasiado la espalda'],
  ['press-mancuernas-declinado', 'Decline_Dumbbell_Bench_Press', 'Press declinado con mancuernas', 'empuje_h', 'mancuerna', 'pecho', 'triceps', 'Piernas sujetas | Recorrido completo', 'Rebotar abajo'],
  ['press-mancuernas-neutro', 'Dumbbell_Bench_Press_with_Neutral_Grip', 'Press con mancuernas agarre neutro', 'empuje_h', 'mancuerna', 'pecho,triceps', 'delt_ant', 'Palmas enfrentadas | Codos cerca del cuerpo', 'Separar las mancuernas arriba'],
  ['press-maquina', 'Leverage_Chest_Press', 'Press de pecho en máquina', 'empuje_h', 'maquina', 'pecho', 'triceps,delt_ant', 'Asiento con manillas a la altura del pecho | Escápulas atrás', 'Despegar la espalda del respaldo'],
  ['press-maquina-inclinado', 'Leverage_Incline_Chest_Press', 'Press inclinado en máquina', 'empuje_h', 'maquina', 'pecho', 'delt_ant', 'Manillas a la parte alta del pecho | Recorrido completo', 'Hombros hacia adelante'],
  ['press-maquina-declinado', 'Leverage_Decline_Chest_Press', 'Press declinado en máquina', 'empuje_h', 'maquina', 'pecho', 'triceps', 'Controla la vuelta | Pecho arriba', 'Recorrido corto'],
  ['press-smith', 'Smith_Machine_Bench_Press', 'Press de banca en Smith', 'empuje_h', 'smith', 'pecho', 'triceps', 'Banco centrado bajo la barra | Baja al pecho', 'Banco mal ubicado'],
  ['press-smith-inclinado', 'Smith_Machine_Incline_Bench_Press', 'Press inclinado en Smith', 'empuje_h', 'smith', 'pecho', 'delt_ant', 'Banco a 30° | Barra a la parte alta del pecho', 'Bajar al cuello'],
  ['aperturas-mancuernas', 'Dumbbell_Flyes', 'Aperturas con mancuernas', 'aislamiento', 'mancuerna', 'pecho', 'delt_ant', 'Codos levemente flectados y fijos | Abre hasta sentir el estiramiento', 'Convertirlo en press'],
  ['aperturas-inclinadas', 'Incline_Dumbbell_Flyes', 'Aperturas inclinadas con mancuernas', 'aislamiento', 'mancuerna', 'pecho', 'delt_ant', 'Banco a 30° | Arco amplio y controlado', 'Bajar demasiado con mucho peso'],
  ['pec-deck', 'Butterfly', 'Pec deck (máquina de aperturas)', 'aislamiento', 'maquina', 'pecho', '', 'Codos a la altura de los hombros | Aprieta 1 s al cerrar', 'Hombros hacia adelante'],
  ['cruce-poleas', 'Cable_Crossover', 'Cruce de poleas', 'aislamiento', 'polea', 'pecho', 'delt_ant', 'Paso adelante, torso levemente inclinado | Cierra las manos al frente', 'Doblar los codos en exceso'],
  ['cruce-poleas-bajo', 'Low_Cable_Crossover', 'Cruce de poleas de abajo hacia arriba', 'aislamiento', 'polea', 'pecho', 'delt_ant', 'Poleas abajo | Sube las manos a la altura del pecho', 'Usar la espalda'],
  ['aperturas-polea-inclinado', 'Incline_Cable_Flye', 'Aperturas en polea (banco inclinado)', 'aislamiento', 'polea', 'pecho', '', 'Banco inclinado entre poleas | Arco controlado', 'Codos que se estiran'],
  ['aperturas-polea-plano', 'Flat_Bench_Cable_Flyes', 'Aperturas en polea (banco plano)', 'aislamiento', 'polea', 'pecho', '', 'Tensión constante | Pausa al cerrar', 'Bajar demasiado'],
  ['press-polea', 'Cable_Chest_Press', 'Press de pecho en polea', 'empuje_h', 'polea', 'pecho', 'triceps', 'De pie, paso adelante | Empuja al frente', 'Arquear la espalda'],
  ['flexiones', 'Pushups', 'Flexiones de brazos', 'empuje_h', 'corporal', 'pecho', 'triceps,delt_ant,abdomen', 'Cuerpo en línea recta | Pecho casi toca el piso', 'Cadera que cae'],
  ['flexiones-abiertas', 'Push-Up_Wide', 'Flexiones abiertas', 'empuje_h', 'corporal', 'pecho', 'delt_ant', 'Manos más anchas que los hombros | Controla la bajada', 'Codos a 90° del cuerpo'],
  ['flexiones-pies-elevados', 'Push-Ups_With_Feet_Elevated', 'Flexiones con pies elevados', 'empuje_h', 'corporal', 'pecho', 'delt_ant,triceps', 'Pies sobre un banco | Cuerpo recto', 'Cadera alta'],
  ['flexiones-inclinadas', 'Incline_Push-Up', 'Flexiones inclinadas (manos elevadas)', 'empuje_h', 'corporal', 'pecho', 'triceps', 'Manos en un banco | Buena opción para principiantes', 'Cadera que cae'],
  ['flexiones-diamante', 'Push-Ups_-_Close_Triceps_Position', 'Flexiones cerradas (tríceps)', 'empuje_h', 'corporal', 'triceps', 'pecho', 'Manos juntas bajo el pecho | Codos pegados', 'Codos abiertos'],
  ['fondos-pecho', 'Dips_-_Chest_Version', 'Fondos en paralelas (pecho)', 'empuje_v', 'corporal', 'pecho', 'triceps,delt_ant', 'Torso inclinado adelante | Baja hasta ~90° de codo', 'Bajar demasiado con hombros adelantados'],
  ['pullover-mancuerna', 'Straight-Arm_Dumbbell_Pullover', 'Pullover con mancuerna', 'aislamiento', 'mancuerna', 'pecho,dorsal', 'triceps', 'Espalda alta en el banco | Brazos casi extendidos', 'Doblar mucho los codos'],

  // ── Espalda: tirón vertical ──
  ['dominadas', 'Pullups', 'Dominadas', 'tiron_v', 'corporal', 'dorsal', 'biceps,esp_media', 'Agarre prono al ancho de hombros | Sube hasta pasar la barbilla | Baja completo', 'Balancearse | Medio recorrido'],
  ['dominadas-supinas', 'Chin-Up', 'Dominadas supinas (chin-up)', 'tiron_v', 'corporal', 'dorsal,biceps', 'esp_media', 'Palmas hacia ti | Pecho hacia la barra', 'Encoger los hombros'],
  ['dominadas-lastradas', 'Weighted_Pull_Ups', 'Dominadas lastradas', 'tiron_v', 'corporal', 'dorsal', 'biceps', 'Cinturón con disco | Recorrido completo', 'Sacrificar recorrido por peso'],
  ['dominadas-asistidas', 'Band_Assisted_Pull-Up', 'Dominadas asistidas con banda', 'tiron_v', 'banda', 'dorsal', 'biceps', 'Banda bajo las rodillas o pies | Reduce la ayuda con el tiempo', 'Rebotar con la banda'],
  ['dominadas-neutras', 'V-Bar_Pullup', 'Dominadas agarre neutro', 'tiron_v', 'corporal', 'dorsal', 'biceps', 'Palmas enfrentadas | Pecho hacia arriba', 'Balanceo'],
  ['jalon-pecho', 'Wide-Grip_Lat_Pulldown', 'Jalón al pecho', 'tiron_v', 'polea', 'dorsal', 'biceps,esp_media', 'Muslos sujetos | Lleva la barra a la parte alta del pecho | Codos hacia abajo y atrás', 'Tirar detrás de la nuca | Balancear el torso'],
  ['jalon-cerrado', 'Close-Grip_Front_Lat_Pulldown', 'Jalón al pecho agarre cerrado', 'tiron_v', 'polea', 'dorsal', 'biceps', 'Manos al ancho de hombros | Pecho arriba', 'Tirar con los brazos'],
  ['jalon-triangulo', 'V-Bar_Pulldown', 'Jalón con triángulo', 'tiron_v', 'polea', 'dorsal', 'biceps,esp_media', 'Agarre neutro | Codos pegados al bajar', 'Inclinarse mucho atrás'],
  ['jalon-supino', 'Underhand_Cable_Pulldowns', 'Jalón agarre supino', 'tiron_v', 'polea', 'dorsal,biceps', '', 'Palmas hacia ti | Lleva la barra al pecho', 'Usar impulso'],
  ['jalon-unilateral', 'One_Arm_Lat_Pulldown', 'Jalón a un brazo', 'tiron_v', 'polea', 'dorsal', 'biceps', 'Un brazo a la vez | Codo hacia la cadera', 'Rotar el torso', true],
  ['pullover-polea', 'Straight-Arm_Pulldown', 'Pullover en polea (brazos rectos)', 'aislamiento', 'polea', 'dorsal', 'triceps', 'Brazos casi rectos | Lleva la barra a los muslos', 'Doblar los codos'],
  ['pullover-polea-cuerda', 'Rope_Straight-Arm_Pulldown', 'Pullover en polea con cuerda', 'aislamiento', 'polea', 'dorsal', '', 'Abre la cuerda al final | Tensión constante', 'Encoger los hombros'],

  // ── Espalda: tirón horizontal ──
  ['remo-barra', 'Bent_Over_Barbell_Row', 'Remo con barra', 'tiron_h', 'barra', 'esp_media,dorsal', 'biceps,delt_post,lumbar', 'Torso inclinado ~45°, espalda neutra | Lleva la barra al ombligo | Junta las escápulas', 'Levantar el torso para subir la barra'],
  ['remo-barra-supino', 'Reverse_Grip_Bent-Over_Rows', 'Remo con barra agarre supino', 'tiron_h', 'barra', 'dorsal,esp_media', 'biceps', 'Palmas hacia arriba | Codos pegados', 'Balancear el torso'],
  ['remo-t', 'T-Bar_Row_with_Handle', 'Remo en barra T', 'tiron_h', 'barra', 'esp_media,dorsal', 'biceps,delt_post', 'Pecho arriba, espalda neutra | Tira hacia el abdomen', 'Redondear la espalda'],
  ['remo-t-apoyado', 'Lying_T-Bar_Row', 'Remo en barra T con apoyo de pecho', 'tiron_h', 'maquina', 'esp_media,dorsal', 'biceps', 'Pecho apoyado | Junta las escápulas', 'Despegar el pecho'],
  ['remo-mancuerna', 'One-Arm_Dumbbell_Row', 'Remo con mancuerna a un brazo', 'tiron_h', 'mancuerna', 'dorsal,esp_media', 'biceps,delt_post', 'Rodilla y mano en el banco | Codo hacia la cadera', 'Rotar el torso', true],
  ['remo-mancuernas', 'Bent_Over_Two-Dumbbell_Row', 'Remo con dos mancuernas', 'tiron_h', 'mancuerna', 'esp_media,dorsal', 'biceps', 'Torso inclinado | Codos atrás', 'Encorvar la espalda'],
  ['remo-mancuernas-inclinado', 'Dumbbell_Incline_Row', 'Remo con mancuernas en banco inclinado', 'tiron_h', 'mancuerna', 'esp_media,dorsal', 'delt_post', 'Pecho apoyado en banco a 30° | Junta escápulas', 'Encoger los hombros'],
  ['remo-sentado-polea', 'Seated_Cable_Rows', 'Remo sentado en polea', 'tiron_h', 'polea', 'esp_media,dorsal', 'biceps', 'Torso erguido | Lleva el agarre al abdomen | Pausa con escápulas juntas', 'Balancear el torso'],
  ['remo-polea-unilateral', 'Seated_One-arm_Cable_Pulley_Rows', 'Remo en polea a un brazo', 'tiron_h', 'polea', 'dorsal,esp_media', 'biceps', 'Un brazo a la vez | Estira adelante y tira atrás', 'Rotar demasiado', true],
  ['remo-maquina', 'Leverage_Iso_Row', 'Remo en máquina', 'tiron_h', 'maquina', 'esp_media,dorsal', 'biceps', 'Pecho en el apoyo | Tira con los codos', 'Despegar el pecho'],
  ['remo-alto-maquina', 'Leverage_High_Row', 'Remo alto en máquina', 'tiron_h', 'maquina', 'dorsal,esp_media', 'delt_post', 'Tira hacia abajo y atrás | Controla la vuelta', 'Encoger los hombros'],
  ['remo-smith', 'Smith_Machine_Bent_Over_Row', 'Remo en Smith', 'tiron_h', 'smith', 'esp_media,dorsal', 'biceps', 'Torso inclinado | Barra al abdomen', 'Espalda redondeada'],
  ['remo-invertido', 'Inverted_Row', 'Remo invertido', 'tiron_h', 'corporal', 'esp_media,dorsal', 'biceps,delt_post', 'Cuerpo recto bajo una barra | Pecho a la barra', 'Cadera que cae'],
  ['remo-meadows', 'One-Arm_Long_Bar_Row', 'Remo con barra a un brazo (landmine)', 'tiron_h', 'barra', 'dorsal,esp_media', 'biceps', 'Barra anclada en una esquina | Codo hacia atrás', 'Girar el torso', true],
  ['remo-kettlebell', 'One-Arm_Kettlebell_Row', 'Remo con kettlebell', 'tiron_h', 'kettlebell', 'dorsal,esp_media', 'biceps', 'Espalda neutra | Codo hacia la cadera', 'Tirar con el bíceps', true],
  ['face-pull', 'Face_Pull', 'Face pull', 'tiron_h', 'polea', 'delt_post,esp_media', 'trapecio', 'Cuerda a la altura de la cara | Tira separando las manos | Codos altos', 'Tirar hacia el pecho'],

  // ── Trapecio ──
  ['encogimientos-barra', 'Barbell_Shrug', 'Encogimientos con barra', 'aislamiento', 'barra', 'trapecio', 'antebrazo', 'Sube los hombros hacia las orejas | Pausa arriba', 'Girar los hombros'],
  ['encogimientos-mancuernas', 'Dumbbell_Shrug', 'Encogimientos con mancuernas', 'aislamiento', 'mancuerna', 'trapecio', '', 'Brazos rectos | Sube y baja controlado', 'Doblar los codos'],
  ['encogimientos-smith', 'Smith_Machine_Behind_the_Back_Shrug', 'Encogimientos en Smith', 'aislamiento', 'smith', 'trapecio', '', 'Barra detrás del cuerpo | Recorrido vertical', 'Rebotar'],
  ['encogimientos-polea', 'Cable_Shrugs', 'Encogimientos en polea', 'aislamiento', 'polea', 'trapecio', '', 'Tensión constante | Pausa arriba', 'Recorrido corto'],
  ['paseo-granjero', 'Farmers_Walk', 'Paseo del granjero', 'acarreo', 'mancuerna', 'trapecio,antebrazo', 'abdomen,gluteos', 'Pesos pesados a los costados | Camina erguido con pasos cortos', 'Inclinarse hacia un lado'],

  // ── Hombros ──
  ['press-militar', 'Standing_Military_Press', 'Press militar de pie', 'empuje_v', 'barra', 'delt_ant', 'triceps,delt_lat,abdomen', 'Glúteos y abdomen apretados | Barra sube pegada a la cara | Termina con la cabeza entre los brazos', 'Arquear la zona lumbar'],
  ['press-militar-sentado', 'Seated_Barbell_Military_Press', 'Press militar sentado', 'empuje_v', 'barra', 'delt_ant', 'triceps,delt_lat', 'Espalda apoyada | Baja a la altura de la barbilla', 'Bajar detrás de la nuca'],
  ['press-hombro-mancuernas', 'Dumbbell_Shoulder_Press', 'Press de hombro con mancuernas', 'empuje_v', 'mancuerna', 'delt_ant', 'triceps,delt_lat', 'Mancuernas a la altura de las orejas | Sube sin chocarlas', 'Arquear la espalda'],
  ['press-hombro-sentado', 'Seated_Dumbbell_Press', 'Press de hombro sentado con mancuernas', 'empuje_v', 'mancuerna', 'delt_ant', 'triceps,delt_lat', 'Respaldo casi vertical | Recorrido completo', 'Bajar poco'],
  ['press-arnold', 'Arnold_Dumbbell_Press', 'Press Arnold', 'empuje_v', 'mancuerna', 'delt_ant,delt_lat', 'triceps', 'Empieza con palmas hacia ti | Rota al subir', 'Hacerlo muy rápido'],
  ['press-hombro-maquina', 'Machine_Shoulder_Military_Press', 'Press de hombro en máquina', 'empuje_v', 'maquina', 'delt_ant', 'triceps,delt_lat', 'Manillas a la altura de los hombros | Espalda apoyada', 'Despegar la espalda'],
  ['press-hombro-smith', 'Smith_Machine_Overhead_Shoulder_Press', 'Press de hombro en Smith', 'empuje_v', 'smith', 'delt_ant', 'triceps', 'Banco vertical bajo la barra | Baja a la barbilla', 'Bajar detrás de la nuca'],
  ['press-hombro-kettlebell', 'Two-Arm_Kettlebell_Military_Press', 'Press de hombro con kettlebells', 'empuje_v', 'kettlebell', 'delt_ant', 'triceps', 'Kettlebells en posición de rack | Sube vertical', 'Arquear la espalda'],
  ['push-press', 'Push_Press', 'Push press', 'empuje_v', 'barra', 'delt_ant', 'triceps,cuadriceps', 'Pequeña flexión de piernas | Impulsa y termina con los brazos', 'Flexión muy profunda'],
  ['elevaciones-laterales', 'Side_Lateral_Raise', 'Elevaciones laterales con mancuernas', 'aislamiento', 'mancuerna', 'delt_lat', 'trapecio', 'Codos levemente flectados | Sube hasta la altura de los hombros | Baja lento', 'Balancear el cuerpo | Subir con los trapecios'],
  ['elevaciones-laterales-sentado', 'Seated_Side_Lateral_Raise', 'Elevaciones laterales sentado', 'aislamiento', 'mancuerna', 'delt_lat', '', 'Sin impulso | Controla la bajada', 'Subir por sobre los hombros'],
  ['elevaciones-laterales-polea', 'Standing_Low-Pulley_Deltoid_Raise', 'Elevación lateral en polea', 'aislamiento', 'polea', 'delt_lat', '', 'Polea baja, un brazo | Tensión constante', 'Girar el torso', true],
  ['elevacion-lateral-inclinada', 'One-Arm_Incline_Lateral_Raise', 'Elevación lateral en banco inclinado', 'aislamiento', 'mancuerna', 'delt_lat', '', 'De lado sobre banco inclinado | Recorrido completo', 'Usar impulso', true],
  ['elevaciones-frontales', 'Front_Dumbbell_Raise', 'Elevaciones frontales con mancuernas', 'aislamiento', 'mancuerna', 'delt_ant', '', 'Sube a la altura de los ojos | Sin balanceo', 'Arquear la espalda'],
  ['elevacion-frontal-polea', 'Front_Cable_Raise', 'Elevación frontal en polea', 'aislamiento', 'polea', 'delt_ant', '', 'De espaldas a la polea | Brazos casi rectos', 'Balanceo'],
  ['elevacion-frontal-disco', 'Front_Plate_Raise', 'Elevación frontal con disco', 'aislamiento', 'otro', 'delt_ant', '', 'Disco con ambas manos | Controla la bajada', 'Usar la espalda'],
  ['pajaros', 'Seated_Bent-Over_Rear_Delt_Raise', 'Pájaros (vuelos posteriores)', 'aislamiento', 'mancuerna', 'delt_post', 'esp_media', 'Torso inclinado | Abre los brazos hacia los lados', 'Juntar las escápulas en exceso'],
  ['pajaros-banco', 'Dumbbell_Lying_Rear_Lateral_Raise', 'Pájaros apoyado en banco', 'aislamiento', 'mancuerna', 'delt_post', '', 'Pecho en banco inclinado | Brazos en arco', 'Balanceo'],
  ['pec-deck-inverso', 'Reverse_Machine_Flyes', 'Pec deck inverso', 'aislamiento', 'maquina', 'delt_post', 'esp_media', 'Pecho en el respaldo | Abre con los codos', 'Encoger los hombros'],
  ['pajaros-polea', 'Cable_Rear_Delt_Fly', 'Pájaros en polea', 'aislamiento', 'polea', 'delt_post', '', 'Poleas cruzadas | Abre a la altura de los hombros', 'Tirar con la espalda'],
  ['separacion-banda', 'Band_Pull_Apart', 'Separación con banda', 'aislamiento', 'banda', 'delt_post', 'esp_media', 'Brazos al frente | Separa la banda hasta el pecho', 'Arquear la espalda'],
  ['remo-al-menton', 'Upright_Barbell_Row', 'Remo al mentón con barra', 'aislamiento', 'barra', 'delt_lat', 'trapecio', 'Agarre algo abierto | Sube los codos hasta los hombros', 'Subir por sobre los hombros'],
  ['remo-al-menton-polea', 'Upright_Cable_Row', 'Remo al mentón en polea', 'aislamiento', 'polea', 'delt_lat', 'trapecio', 'Codos lideran el movimiento | Controla la bajada', 'Agarre demasiado cerrado'],
  ['rotacion-externa-polea', 'External_Rotation_with_Cable', 'Rotación externa en polea', 'aislamiento', 'polea', 'delt_post', '', 'Codo pegado al cuerpo | Gira el antebrazo hacia afuera', 'Separar el codo', true],

  // ── Bíceps ──
  ['curl-barra', 'Barbell_Curl', 'Curl de bíceps con barra', 'aislamiento', 'barra', 'biceps', 'antebrazo', 'Codos fijos a los costados | Sube sin balancear | Baja controlado', 'Balancear el torso'],
  ['curl-ez', 'EZ-Bar_Curl', 'Curl con barra Z', 'aislamiento', 'ez', 'biceps', 'antebrazo', 'Agarre en la curva interna | Codos quietos', 'Mover los codos hacia adelante'],
  ['curl-mancuernas', 'Dumbbell_Bicep_Curl', 'Curl de bíceps con mancuernas', 'aislamiento', 'mancuerna', 'biceps', '', 'Gira la palma hacia arriba al subir | Recorrido completo', 'Balanceo'],
  ['curl-alterno', 'Dumbbell_Alternate_Bicep_Curl', 'Curl alterno con mancuernas', 'aislamiento', 'mancuerna', 'biceps', '', 'Un brazo a la vez | Supina al subir', 'Mover el hombro'],
  ['curl-martillo', 'Hammer_Curls', 'Curl martillo', 'aislamiento', 'mancuerna', 'biceps,antebrazo', '', 'Palmas enfrentadas todo el recorrido | Codos fijos', 'Balanceo'],
  ['curl-martillo-cruzado', 'Cross_Body_Hammer_Curl', 'Curl martillo cruzado', 'aislamiento', 'mancuerna', 'biceps,antebrazo', '', 'Lleva la mancuerna hacia el hombro opuesto', 'Mover el torso'],
  ['curl-inclinado', 'Incline_Dumbbell_Curl', 'Curl inclinado con mancuernas', 'aislamiento', 'mancuerna', 'biceps', '', 'Banco a 45°, brazos colgando | Estiramiento completo abajo', 'Adelantar los codos'],
  ['curl-predicador', 'Preacher_Curl', 'Curl predicador con barra', 'aislamiento', 'ez', 'biceps', '', 'Axilas en el borde del banco | No bloquees abajo', 'Levantar los codos del apoyo'],
  ['curl-predicador-mancuerna', 'One_Arm_Dumbbell_Preacher_Curl', 'Curl predicador a un brazo', 'aislamiento', 'mancuerna', 'biceps', '', 'Brazo apoyado | Baja lento', 'Rebotar abajo', true],
  ['curl-maquina', 'Machine_Preacher_Curls', 'Curl de bíceps en máquina', 'aislamiento', 'maquina', 'biceps', '', 'Codos alineados con el eje | Aprieta arriba', 'Levantar los codos'],
  ['curl-polea', 'Standing_Biceps_Cable_Curl', 'Curl de bíceps en polea', 'aislamiento', 'polea', 'biceps', '', 'Codos fijos | Tensión constante', 'Inclinarse atrás'],
  ['curl-polea-cuerda', 'Cable_Hammer_Curls_-_Rope_Attachment', 'Curl martillo en polea con cuerda', 'aislamiento', 'polea', 'biceps,antebrazo', '', 'Palmas enfrentadas | Codos quietos', 'Usar impulso'],
  ['curl-polea-alta', 'Overhead_Cable_Curl', 'Curl en polea alta', 'aislamiento', 'polea', 'biceps', '', 'Brazos a la altura de los hombros | Lleva las manos a la cabeza', 'Bajar los codos'],
  ['curl-polea-unilateral', 'Standing_One-Arm_Cable_Curl', 'Curl en polea a un brazo', 'aislamiento', 'polea', 'biceps', '', 'De espaldas a la polea para estirar más | Codo detrás del cuerpo', 'Mover el hombro', true],
  ['curl-concentrado', 'Concentration_Curls', 'Curl concentrado', 'aislamiento', 'mancuerna', 'biceps', '', 'Codo apoyado en el muslo | Aprieta arriba', 'Mover el hombro', true],
  ['curl-arana', 'Spider_Curl', 'Curl araña', 'aislamiento', 'ez', 'biceps', '', 'Pecho apoyado en banco inclinado | Brazos colgando', 'Balanceo'],
  ['curl-invertido', 'Reverse_Barbell_Curl', 'Curl invertido con barra', 'aislamiento', 'barra', 'antebrazo,biceps', '', 'Palmas hacia abajo | Codos fijos', 'Muñecas dobladas'],
  ['curl-zottman', 'Zottman_Curl', 'Curl Zottman', 'aislamiento', 'mancuerna', 'biceps,antebrazo', '', 'Sube con palmas arriba | Gira y baja con palmas abajo', 'Bajar rápido'],
  ['curl-arrastre', 'Drag_Curl', 'Curl arrastrado (drag curl)', 'aislamiento', 'barra', 'biceps', '', 'Barra pegada al cuerpo | Codos van atrás', 'Adelantar los codos'],

  // ── Tríceps ──
  ['extension-triceps-polea', 'Triceps_Pushdown', 'Extensión de tríceps en polea', 'aislamiento', 'polea', 'triceps', '', 'Codos pegados al cuerpo | Extiende completo abajo', 'Mover los codos | Inclinarse sobre la barra'],
  ['extension-triceps-cuerda', 'Triceps_Pushdown_-_Rope_Attachment', 'Extensión de tríceps con cuerda', 'aislamiento', 'polea', 'triceps', '', 'Abre la cuerda al final | Codos fijos', 'Usar los hombros'],
  ['extension-triceps-v', 'Triceps_Pushdown_-_V-Bar_Attachment', 'Extensión de tríceps con barra V', 'aislamiento', 'polea', 'triceps', '', 'Codos fijos | Pausa abajo', 'Recorrido corto'],
  ['extension-triceps-inversa', 'Reverse_Grip_Triceps_Pushdown', 'Extensión de tríceps agarre supino', 'aislamiento', 'polea', 'triceps', '', 'Palmas hacia arriba | Codos pegados', 'Muñecas dobladas'],
  ['extension-triceps-trasnuca-cuerda', 'Triceps_Overhead_Extension_with_Rope', 'Extensión de tríceps sobre la cabeza con cuerda', 'aislamiento', 'polea', 'triceps', '', 'De espaldas a la polea | Codos apuntando al frente', 'Abrir los codos'],
  ['extension-triceps-unilateral', 'Cable_One_Arm_Tricep_Extension', 'Extensión de tríceps a un brazo en polea', 'aislamiento', 'polea', 'triceps', '', 'Un brazo a la vez | Codo fijo', 'Rotar el torso', true],
  ['press-frances', 'EZ-Bar_Skullcrusher', 'Press francés con barra Z', 'aislamiento', 'ez', 'triceps', '', 'Codos apuntando al techo | Baja hacia la frente', 'Abrir los codos'],
  ['press-frances-mancuernas', 'Lying_Dumbbell_Tricep_Extension', 'Press francés con mancuernas', 'aislamiento', 'mancuerna', 'triceps', '', 'Palmas enfrentadas | Baja a los costados de la cabeza', 'Mover los hombros'],
  ['extension-triceps-mancuerna', 'Standing_Dumbbell_Triceps_Extension', 'Extensión de tríceps sobre la cabeza con mancuerna', 'aislamiento', 'mancuerna', 'triceps', '', 'Mancuerna con ambas manos | Baja detrás de la cabeza', 'Arquear la espalda'],
  ['extension-triceps-mancuerna-1', 'Dumbbell_One-Arm_Triceps_Extension', 'Extensión de tríceps a un brazo con mancuerna', 'aislamiento', 'mancuerna', 'triceps', '', 'Codo apuntando arriba | Recorrido completo', 'Abrir el codo', true],
  ['patada-triceps', 'Tricep_Dumbbell_Kickback', 'Patada de tríceps', 'aislamiento', 'mancuerna', 'triceps', '', 'Brazo paralelo al piso | Extiende y aprieta', 'Balancear el brazo', true],
  ['fondos-triceps', 'Dips_-_Triceps_Version', 'Fondos en paralelas (tríceps)', 'empuje_v', 'corporal', 'triceps', 'pecho,delt_ant', 'Torso vertical | Codos hacia atrás', 'Bajar demasiado'],
  ['fondos-banco', 'Bench_Dips', 'Fondos en banco', 'empuje_v', 'corporal', 'triceps', 'pecho', 'Manos en el borde del banco | Baja hasta ~90°', 'Hombros hacia adelante'],
  ['fondos-maquina', 'Dip_Machine', 'Fondos en máquina', 'empuje_v', 'maquina', 'triceps', 'pecho', 'Codos pegados | Extiende completo', 'Encoger los hombros'],
  ['extension-triceps-maquina', 'Machine_Triceps_Extension', 'Extensión de tríceps en máquina', 'aislamiento', 'maquina', 'triceps', '', 'Codos alineados con el eje | Controla la vuelta', 'Levantar los codos'],
  ['press-jm', 'JM_Press', 'Press JM', 'empuje_h', 'barra', 'triceps', 'pecho', 'Híbrido entre press cerrado y press francés | Baja la barra hacia la barbilla', 'Mucho peso con mala técnica'],

  // ── Antebrazo ──
  ['curl-muneca', 'Palms-Up_Barbell_Wrist_Curl_Over_A_Bench', 'Curl de muñeca con barra', 'aislamiento', 'barra', 'antebrazo', '', 'Antebrazos sobre el banco | Solo mueve la muñeca', 'Mover los codos'],
  ['curl-muneca-inverso', 'Palms-Down_Wrist_Curl_Over_A_Bench', 'Curl de muñeca inverso', 'aislamiento', 'barra', 'antebrazo', '', 'Palmas hacia abajo | Recorrido completo', 'Usar mucho peso'],
  ['rodillo-muneca', 'Wrist_Roller', 'Rodillo de muñeca', 'aislamiento', 'otro', 'antebrazo', '', 'Brazos al frente | Enrolla y desenrolla lento', 'Bajar los brazos'],

  // ── Core ──
  ['plancha', 'Plank', 'Plancha', 'core', 'corporal', 'abdomen', '', 'Codos bajo los hombros | Cuerpo recto, glúteos apretados', 'Cadera alta o caída'],
  ['plancha-lateral', 'Side_Bridge', 'Plancha lateral', 'core', 'corporal', 'abdomen', 'abductores', 'Codo bajo el hombro | Cadera arriba', 'Cadera que cae', true],
  ['crunch', 'Crunches', 'Abdominales (crunch)', 'core', 'corporal', 'abdomen', '', 'Despega solo los hombros | Exhala al subir', 'Tirar del cuello'],
  ['crunch-polea', 'Cable_Crunch', 'Crunch en polea', 'core', 'polea', 'abdomen', '', 'De rodillas, cuerda junto a la cabeza | Enrolla la columna', 'Moverse desde la cadera'],
  ['crunch-maquina', 'Ab_Crunch_Machine', 'Crunch en máquina', 'core', 'maquina', 'abdomen', '', 'Enrolla el tronco | Controla la vuelta', 'Tirar con los brazos'],
  ['crunch-declinado', 'Decline_Crunch', 'Crunch declinado', 'core', 'corporal', 'abdomen', '', 'Pies sujetos | Sube enrollando', 'Impulso con la cabeza'],
  ['crunch-inverso', 'Reverse_Crunch', 'Crunch inverso', 'core', 'corporal', 'abdomen', '', 'Lleva las rodillas al pecho | Despega la pelvis', 'Usar impulso'],
  ['elevacion-piernas-colgado', 'Hanging_Leg_Raise', 'Elevación de piernas colgado', 'core', 'corporal', 'abdomen', '', 'Cuelga de la barra | Sube las piernas sin balanceo', 'Balancearse'],
  ['elevacion-rodillas-paralelas', 'Knee_Hip_Raise_On_Parallel_Bars', 'Elevación de rodillas en paralelas', 'core', 'corporal', 'abdomen', '', 'Antebrazos apoyados | Rodillas al pecho', 'Balanceo'],
  ['elevacion-piernas-banco', 'Flat_Bench_Lying_Leg_Raise', 'Elevación de piernas en banco', 'core', 'corporal', 'abdomen', '', 'Zona lumbar pegada | Baja sin tocar el piso', 'Arquear la espalda'],
  ['rueda-abdominal', 'Ab_Roller', 'Rueda abdominal', 'core', 'otro', 'abdomen', 'dorsal', 'Desde rodillas | Avanza manteniendo la espalda neutra', 'Hundir la zona lumbar'],
  ['giro-ruso', 'Russian_Twist', 'Giro ruso', 'core', 'corporal', 'abdomen', '', 'Torso inclinado | Gira de lado a lado', 'Encorvar la espalda'],
  ['pallof', 'Pallof_Press', 'Press Pallof', 'core', 'polea', 'abdomen', '', 'De lado a la polea | Empuja al frente sin girar', 'Rotar el torso', true],
  ['lenador', 'Standing_Cable_Wood_Chop', 'Leñador en polea', 'core', 'polea', 'abdomen', '', 'Gira desde el tronco | Brazos casi rectos', 'Tirar con los brazos', true],
  ['dead-bug', 'Dead_Bug', 'Dead bug', 'core', 'corporal', 'abdomen', '', 'Zona lumbar pegada al piso | Brazo y pierna contrarios', 'Arquear la espalda'],
  ['sit-up', 'Sit-Up', 'Abdominales completos (sit-up)', 'core', 'corporal', 'abdomen', '', 'Pies apoyados | Sube controlado', 'Tirar del cuello'],
  ['escaladores', 'Mountain_Climbers', 'Escaladores', 'core', 'corporal', 'abdomen', 'cuadriceps', 'Posición de plancha | Alterna rodillas al pecho', 'Cadera alta'],

  // ── Olímpicos y potencia ──
  ['cargada-potencia', 'Power_Clean', 'Cargada de potencia (power clean)', 'bisagra', 'barra', 'isquios,gluteos,trapecio', 'cuadriceps,delt_ant', 'Tira explosivo desde el piso | Recibe la barra en los hombros', 'Tirar con los brazos'],
  ['cargada-colgante', 'Hang_Clean', 'Cargada colgante (hang clean)', 'bisagra', 'barra', 'isquios,gluteos,trapecio', 'cuadriceps', 'Empieza sobre las rodillas | Extensión explosiva de cadera', 'Doblar los brazos antes de tiempo'],
  ['arrancada', 'Snatch', 'Arrancada', 'bisagra', 'barra', 'cuadriceps,gluteos,trapecio', 'delt_ant', 'Agarre ancho | Recibe la barra sobre la cabeza en sentadilla', 'Barra lejos del cuerpo'],
  ['envion', 'Clean_and_Jerk', 'Dos tiempos (clean and jerk)', 'bisagra', 'barra', 'cuadriceps,gluteos,delt_ant', 'trapecio,triceps', 'Cargada a hombros y luego envión | Técnica antes que peso', 'Saltarse la progresión técnica'],
  ['thruster-kettlebell', 'Kettlebell_Thruster', 'Thruster con kettlebell', 'sentadilla', 'kettlebell', 'cuadriceps,delt_ant', 'gluteos,triceps', 'Sentadilla y press en un solo movimiento', 'Separar las fases'],
];
