// Base de alimentos de Forus.
// FOODS: [id, nombre, grupo, claves USDA (SR Legacy), porciones propias "Nombre:g|Nombre:g"]
//   Las claves son fragmentos separados por coma que deben aparecer en la descripción USDA;
//   si hay varias coincidencias se usa la descripción más corta. Si el alimento es una
//   referencia aproximada (no existe tal cual en USDA) el nombre lo dice con "(ref. …)".
// CUSTOM: alimentos sin equivalente USDA, con valores por 100 g.
// RECIPES: preparaciones calculadas desde sus ingredientes (gramos crudos) y un rendimiento.

export const GROUPS = {
  lacteos: 'Lácteos y huevos', grasas: 'Aceites y grasas', aves: 'Pollo y pavo', vacuno: 'Vacuno y otras carnes',
  cerdo: 'Cerdo', embutidos: 'Embutidos', pescados: 'Pescados y mariscos', legumbres: 'Legumbres y soya',
  cereales: 'Cereales, arroz y pastas', panes: 'Panes y masas', verduras: 'Verduras', frutas: 'Frutas',
  frutos_secos: 'Frutos secos y semillas', dulces: 'Dulces y postres', bebidas: 'Bebidas', snacks: 'Snacks',
  salsas: 'Salsas y condimentos', suplementos: 'Suplementos', comida_rapida: 'Comida rápida',
  preparaciones: 'Preparaciones chilenas',
};

export const FOODS = [
  // ── Lácteos y huevos ──
  ['leche-entera', 'Leche entera', 'lacteos', 'Milk, whole, 3.25% milkfat, with added vitamin D', 'Taza:250|Vaso:200'],
  ['leche-semi', 'Leche semidescremada', 'lacteos', 'Milk, reduced fat, fluid, 2% milkfat, with added vitamin A and vitamin D', 'Taza:250|Vaso:200'],
  ['leche-descremada', 'Leche descremada', 'lacteos', 'Milk, nonfat, fluid, with added vitamin A and vitamin D', 'Taza:250|Vaso:200'],
  ['leche-1', 'Leche semidescremada 1 %', 'lacteos', 'Milk, lowfat, fluid, 1% milkfat, with added vitamin A and vitamin D', 'Taza:250'],
  ['leche-polvo-entera', 'Leche en polvo entera', 'lacteos', 'Milk, dry, whole, with added vitamin D', 'Cucharada:8|Medida (26 g):26'],
  ['leche-polvo-descremada', 'Leche en polvo descremada', 'lacteos', 'Milk, dry, nonfat, regular, without added vitamin A', 'Cucharada:7|Medida (20 g):20'],
  ['leche-condensada', 'Leche condensada', 'lacteos', 'Milk, canned, condensed, sweetened', 'Cucharada:20'],
  ['leche-evaporada', 'Leche evaporada', 'lacteos', 'Milk, canned, evaporated, without added vitamin A', 'Cucharada:15'],
  ['leche-chocolate', 'Leche chocolatada', 'lacteos', 'Milk, chocolate, fluid, commercial, reduced fat', 'Caja (200 ml):200'],
  ['yogur-natural', 'Yogur natural', 'lacteos', 'Yogurt, plain, whole milk', 'Pote:155'],
  ['yogur-natural-desc', 'Yogur natural descremado', 'lacteos', 'Yogurt, plain, skim milk', 'Pote:155'],
  ['yogur-griego', 'Yogur griego natural bajo en grasa', 'lacteos', 'Yogurt, Greek, plain, lowfat', 'Pote:150'],
  ['yogur-griego-entero', 'Yogur griego natural entero', 'lacteos', 'Yogurt, Greek, plain, whole milk', 'Pote:150'],
  ['yogur-frutas', 'Yogur batido de frutas', 'lacteos', 'Yogurt, fruit, low fat', 'Pote:125'],
  ['yogur-vainilla', 'Yogur de vainilla', 'lacteos', 'Yogurt, vanilla, low fat', 'Pote:125'],
  ['kefir', 'Kéfir', 'lacteos', 'Kefir', 'Vaso:200'],
  ['quesillo', 'Quesillo (ref. queso fresco)', 'lacteos', 'Cheese, queso fresco', 'Lámina:30|Porción:60'],
  ['queso-cottage', 'Queso cottage', 'lacteos', 'Cheese, cottage, creamed, large or small curd', 'Cucharada:15|Pote chico:125'],
  ['queso-cottage-light', 'Queso cottage light', 'lacteos', 'Cheese, cottage, lowfat, 1% milkfat', 'Cucharada:15|Pote chico:125'],
  ['queso-gauda', 'Queso gauda', 'lacteos', 'Cheese, gouda', 'Lámina:20'],
  ['queso-chanco', 'Queso chanco (ref. tilsit)', 'lacteos', 'Cheese, tilsit', 'Lámina:20'],
  ['queso-mantecoso', 'Queso mantecoso (ref. muenster)', 'lacteos', 'Cheese, muenster', 'Lámina:20'],
  ['queso-cheddar', 'Queso cheddar', 'lacteos', 'Cheese, cheddar', 'Lámina:20'],
  ['queso-mozzarella', 'Queso mozzarella', 'lacteos', 'Cheese, mozzarella, whole milk', 'Lámina:20|Taza rallado:110'],
  ['queso-mozzarella-light', 'Queso mozzarella semidescremado', 'lacteos', 'Cheese, mozzarella, part skim milk', 'Lámina:20'],
  ['queso-parmesano', 'Queso parmesano rallado', 'lacteos', 'Cheese, parmesan, grated', 'Cucharada:5'],
  ['queso-crema', 'Queso crema', 'lacteos', 'Cheese, cream', 'Cucharada:15'],
  ['ricotta', 'Ricotta', 'lacteos', 'Cheese, ricotta, whole milk', 'Cucharada:15'],
  ['ricotta-light', 'Ricotta semidescremada', 'lacteos', 'Cheese, ricotta, part skim milk', 'Cucharada:15'],
  ['queso-feta', 'Queso feta', 'lacteos', 'Cheese, feta', 'Porción:30'],
  ['queso-cabra', 'Queso de cabra', 'lacteos', 'Cheese, goat, soft type', 'Porción:30'],
  ['queso-edam', 'Queso edam', 'lacteos', 'Cheese, edam', 'Lámina:20'],
  ['queso-gruyere', 'Queso gruyère', 'lacteos', 'Cheese, gruyere', 'Lámina:20'],
  ['crema-leche', 'Crema de leche', 'lacteos', 'Cream, fluid, heavy whipping', 'Cucharada:15'],
  ['crema-acida', 'Crema ácida', 'lacteos', 'Cream, sour, cultured', 'Cucharada:15'],
  ['mantequilla', 'Mantequilla', 'lacteos', 'Butter, salted', 'Cucharadita:5|Cucharada:14'],
  ['mantequilla-sin-sal', 'Mantequilla sin sal', 'lacteos', 'Butter, without salt', 'Cucharadita:5|Cucharada:14'],
  ['huevo', 'Huevo entero', 'lacteos', 'Egg, whole, raw, fresh', 'Unidad:50|Unidad grande:60'],
  ['huevo-duro', 'Huevo duro', 'lacteos', 'Egg, whole, cooked, hard-boiled', 'Unidad:50'],
  ['huevo-frito', 'Huevo frito', 'lacteos', 'Egg, whole, cooked, fried', 'Unidad:46'],
  ['huevo-revuelto', 'Huevos revueltos', 'lacteos', 'Egg, whole, cooked, scrambled', 'Porción (2 huevos):120'],
  ['huevo-pochado', 'Huevo pochado', 'lacteos', 'Egg, whole, cooked, poached', 'Unidad:50'],
  ['clara', 'Clara de huevo', 'lacteos', 'Egg, white, raw, fresh', 'Unidad:33'],
  ['yema', 'Yema de huevo', 'lacteos', 'Egg, yolk, raw, fresh', 'Unidad:17'],
  ['leche-soya', 'Leche de soya', 'lacteos', 'Soymilk, original and vanilla, unfortified', 'Taza:250'],
  ['leche-almendra', 'Leche de almendras sin azúcar', 'lacteos', 'Beverages, almond milk, unsweetened', 'Taza:250'],

  // ── Aceites y grasas ──
  ['aceite-oliva', 'Aceite de oliva', 'grasas', 'Oil, olive, salad or cooking', 'Cucharadita:5|Cucharada:14'],
  ['aceite-maravilla', 'Aceite de maravilla', 'grasas', 'Oil, sunflower, linoleic', 'Cucharadita:5|Cucharada:14'],
  ['aceite-canola', 'Aceite de canola', 'grasas', 'Oil, canola', 'Cucharadita:5|Cucharada:14'],
  ['aceite-coco', 'Aceite de coco', 'grasas', 'Oil, coconut', 'Cucharadita:5|Cucharada:14'],
  ['aceite-maiz', 'Aceite de maíz', 'grasas', 'Oil, corn, industrial and retail, all purpose salad or cooking', 'Cucharada:14'],
  ['aceite-pepita-uva', 'Aceite de pepita de uva', 'grasas', 'Oil, grapeseed', 'Cucharada:14'],
  ['margarina', 'Margarina', 'grasas', 'Margarine, regular, hard', 'Cucharadita:5'],
  ['manteca', 'Manteca de cerdo', 'grasas', 'Lard', 'Cucharada:13'],
  ['mayonesa', 'Mayonesa', 'grasas', 'Salad dressing, mayonnaise, regular', 'Cucharadita:5|Cucharada:14'],
  ['mayonesa-light', 'Mayonesa light', 'grasas', 'Salad dressing, mayonnaise, light', 'Cucharada:15'],

  // ── Pollo y pavo ──
  ['pechuga-cruda', 'Pechuga de pollo cruda', 'aves', 'Chicken, broilers or fryers, breast, meat only, raw', 'Filete:150'],
  ['pechuga-asada', 'Pechuga de pollo a la plancha', 'aves', 'Chicken, broilers or fryers, breast, meat only, cooked, roasted', 'Filete:120|Porción:100'],
  ['pechuga-cocida', 'Pechuga de pollo cocida', 'aves', 'Chicken, broilers or fryers, breast, meat only, cooked, stewed', 'Porción:100'],
  ['pechuga-piel', 'Pechuga de pollo con piel asada', 'aves', 'Chicken, broilers or fryers, breast, meat and skin, cooked, roasted', 'Porción:150'],
  ['pechuga-apanada', 'Pechuga de pollo apanada frita', 'aves', 'Chicken, broilers or fryers, breast, meat and skin, cooked, fried, batter', 'Porción:150'],
  ['trutro-crudo', 'Trutro de pollo con piel crudo', 'aves', 'Chicken, broilers or fryers, thigh, meat and skin, raw', 'Unidad:130'],
  ['trutro-asado', 'Trutro de pollo sin piel asado', 'aves', 'Chicken, broilers or fryers, thigh, meat only, cooked, roasted', 'Unidad:90'],
  ['trutro-piel-asado', 'Trutro de pollo con piel asado', 'aves', 'Chicken, broilers or fryers, thigh, meat and skin, cooked, roasted', 'Unidad:110'],
  ['trutro-corto', 'Trutro corto sin piel asado', 'aves', 'Chicken, broilers or fryers, drumstick, meat only, cooked, roasted', 'Unidad:75'],
  ['trutro-corto-piel', 'Trutro corto con piel asado', 'aves', 'Chicken, broilers or fryers, drumstick, meat and skin, cooked, roasted', 'Unidad:90'],
  ['alitas', 'Alitas de pollo asadas', 'aves', 'Chicken, broilers or fryers, wing, meat and skin, cooked, roasted', 'Unidad:35'],
  ['pollo-asado', 'Pollo asado con piel', 'aves', 'Chicken, broilers or fryers, meat and skin, cooked, roasted', 'Cuarto de pollo:250'],
  ['pollo-asado-sin-piel', 'Pollo asado sin piel', 'aves', 'Chicken, broilers or fryers, meat only, cooked, roasted', 'Porción:150'],
  ['pollo-molido', 'Pollo molido cocido', 'aves', 'Chicken, ground, crumbles, cooked, pan-browned', 'Porción:100'],
  ['higado-pollo', 'Hígado de pollo cocido', 'aves', 'Chicken, liver, all classes, cooked, simmered', 'Porción:100'],
  ['contre', 'Contre de pollo cocido', 'aves', 'Chicken, gizzard, all classes, cooked, simmered', 'Porción:100'],
  ['pavo-pechuga', 'Pechuga de pavo asada', 'aves', 'Turkey, whole, breast, meat only, cooked, roasted', 'Porción:120'],
  ['pavo-trutro', 'Trutro de pavo asado', 'aves', 'Turkey, whole, dark meat, cooked, roasted', 'Porción:120'],
  ['pavo-molido', 'Pavo molido cocido', 'aves', 'Turkey, Ground, cooked', 'Porción:100'],
  ['nuggets', 'Nuggets de pollo', 'aves', 'nuggets', 'Unidad:18'],

  // ── Vacuno y otras carnes ──
  ['molida-5-cocida', 'Carne molida 5 % grasa (cocida)', 'vacuno', 'Beef, ground, 95% lean meat / 5% fat, crumbles, cooked, pan-browned', 'Porción:100'],
  ['molida-10-cocida', 'Carne molida 10 % grasa (cocida)', 'vacuno', 'Beef, ground, 90% lean meat / 10% fat, crumbles, cooked, pan-browned', 'Porción:100'],
  ['molida-15-cocida', 'Carne molida 15 % grasa (cocida)', 'vacuno', 'Beef, ground, 85% lean meat / 15% fat, crumbles, cooked, pan-browned', 'Porción:100'],
  ['molida-20-cocida', 'Carne molida 20 % grasa (cocida)', 'vacuno', 'Beef, ground, 80% lean meat / 20% fat, crumbles, cooked, pan-browned', 'Porción:100'],
  ['molida-5-cruda', 'Carne molida 5 % grasa (cruda)', 'vacuno', 'Beef, ground, 95% lean meat / 5% fat, raw', 'Bandeja:500'],
  ['molida-10-cruda', 'Carne molida 10 % grasa (cruda)', 'vacuno', 'Beef, ground, 90% lean meat / 10% fat, raw', 'Bandeja:500'],
  ['molida-15-cruda', 'Carne molida 15 % grasa (cruda)', 'vacuno', 'Beef, ground, 85% lean meat / 15% fat, raw', 'Bandeja:500'],
  ['molida-20-cruda', 'Carne molida 20 % grasa (cruda)', 'vacuno', 'Beef, ground, 80% lean meat / 20% fat, raw', 'Bandeja:500'],
  ['lomo-liso', 'Lomo liso a la plancha', 'vacuno', 'Beef, top loin, steak, separable lean only, cooked, grilled', 'Bistec:150'],
  ['lomo-liso-crudo', 'Lomo liso crudo', 'vacuno', 'Beef, top loin, steak, separable lean only, raw', 'Bistec:180'],
  ['lomo-vetado', 'Lomo vetado a la plancha', 'vacuno', 'Beef, rib eye, separable lean and fat, cooked', 'Bistec:150'],
  ['filete', 'Filete de vacuno a la plancha', 'vacuno', 'Beef, tenderloin, steak, separable lean only, cooked', 'Medallón:120'],
  ['posta-negra', 'Posta negra a la plancha', 'vacuno', 'Beef, top round, separable lean only, cooked, broiled', 'Bistec:150'],
  ['posta-rosada', 'Posta rosada al horno', 'vacuno', 'Beef, eye of round, separable lean only, cooked', 'Porción:120'],
  ['posta-cruda', 'Posta cruda', 'vacuno', 'Beef, eye of round, separable lean only, raw', 'Porción:150'],
  ['asiento', 'Asiento o punta de picana (ref. sirloin)', 'vacuno', 'Beef, top sirloin, steak, separable lean only, cooked', 'Bistec:150'],
  ['sobrecostilla', 'Sobrecostilla o huachalomo guisado', 'vacuno', 'Beef, chuck, arm pot roast, separable lean only, cooked, braised', 'Porción:150'],
  ['tapapecho', 'Tapapecho guisado', 'vacuno', 'Beef, brisket, flat half, separable lean only, cooked', 'Porción:150'],
  ['plateada', 'Plateada al horno (ref. costilla con grasa)', 'vacuno', 'Beef, rib, whole, separable lean and fat, cooked, roasted', 'Porción:150'],
  ['costilla-vacuno', 'Costillar de vacuno guisado', 'vacuno', 'short ribs, separable lean and fat, cooked', 'Porción:150'],
  ['osobuco', 'Osobuco cocido', 'vacuno', 'Beef, shank crosscuts, separable lean only, cooked', 'Porción:150'],
  ['osobuco-crudo', 'Osobuco crudo', 'vacuno', 'Beef, shank crosscuts, separable lean only, raw', 'Trozo:250'],
  ['entrana', 'Entraña o palanca a la parrilla (ref. flank)', 'vacuno', 'Beef, flank, steak, separable lean only, cooked, broiled', 'Porción:150'],
  ['higado-vacuno', 'Hígado de vacuno frito', 'vacuno', 'Beef, variety meats and by-products, liver, cooked, pan-fried', 'Bistec:100'],
  ['lengua', 'Lengua de vacuno cocida', 'vacuno', 'Beef, variety meats and by-products, tongue, cooked, simmered', 'Porción:100'],
  ['charqui', 'Charqui', 'vacuno', 'Beef, cured, dried', 'Porción:30'],
  ['cordero', 'Pierna de cordero asada', 'vacuno', 'Lamb, New Zealand, imported, frozen, leg, whole (shank and sirloin), separable lean only, cooked, roasted', 'Porción:150'],
  ['chuleta-cordero', 'Chuleta de cordero a la parrilla', 'vacuno', 'Lamb, New Zealand, imported, frozen, loin, separable lean and fat, cooked, broiled', 'Unidad:70'],
  ['conejo', 'Conejo asado', 'vacuno', 'Game meat, rabbit, domesticated, composite of cuts, cooked, roasted', 'Porción:150'],
  ['ternera', 'Ternera guisada', 'vacuno', 'Veal, leg (top round), separable lean only, cooked, braised', 'Porción:150'],

  // ── Cerdo ──
  ['lomo-cerdo', 'Lomo de cerdo a la plancha', 'cerdo', 'Pork, fresh, loin, center loin (chops), bone-in, separable lean only, cooked, broiled', 'Bistec:150'],
  ['lomo-cerdo-crudo', 'Lomo de cerdo crudo', 'cerdo', 'Pork, fresh, loin, center loin (chops), bone-in, separable lean only, raw', 'Bistec:180'],
  ['filete-cerdo', 'Filete de cerdo asado', 'cerdo', 'Pork, fresh, loin, tenderloin, separable lean only, cooked, roasted', 'Porción:120'],
  ['chuleta-cerdo', 'Chuleta de cerdo a la parrilla', 'cerdo', 'Pork, fresh, loin, center rib (chops), bone-in, separable lean and fat, cooked, broiled', 'Unidad:120'],
  ['costillar-cerdo', 'Costillar de cerdo', 'cerdo', 'Pork, fresh, spareribs, separable lean and fat, cooked, braised', 'Porción:200'],
  ['pulpa-cerdo', 'Pulpa de pierna de cerdo asada', 'cerdo', 'Pork, fresh, leg (ham), whole, separable lean only, cooked, roasted', 'Porción:150'],
  ['pernil', 'Pernil de cerdo asado', 'cerdo', 'Pork, fresh, shoulder, whole, separable lean only, cooked, roasted', 'Porción:150'],
  ['molida-cerdo', 'Carne molida de cerdo cocida', 'cerdo', 'Pork, fresh, ground, cooked', 'Porción:100'],
  ['tocino', 'Tocino frito', 'cerdo', 'Pork, cured, bacon, cooked, pan-fried', 'Lonja:8'],
  ['chicharron', 'Chicharrón', 'cerdo', 'Snacks, pork skins, plain', 'Porción:15'],

  // ── Embutidos ──
  ['jamon-cerdo', 'Jamón de cerdo', 'embutidos', 'Ham, sliced, regular (approximately 11% fat)', 'Lámina:15'],
  ['jamon-pavo', 'Jamón de pavo', 'embutidos', 'Ham, turkey, sliced, extra lean, prepackaged or deli', 'Lámina:15'],
  ['pavo-laminado', 'Pechuga de pavo laminada', 'embutidos', 'Turkey breast, sliced', 'Lámina:15'],
  ['vienesa', 'Vienesa (salchicha)', 'embutidos', 'Frankfurter, meat', 'Unidad:45'],
  ['vienesa-pollo', 'Vienesa de pollo', 'embutidos', 'Frankfurter, chicken', 'Unidad:45'],
  ['longaniza', 'Longaniza (ref. salchicha italiana de cerdo)', 'embutidos', 'Sausage, Italian, pork, cooked', 'Trozo:80'],
  ['chorizo', 'Chorizo (crudo)', 'embutidos', 'Sausage, pork, chorizo, link or ground, raw', 'Unidad:100'],
  ['salame', 'Salame', 'embutidos', 'Salami, dry or hard, pork, beef', 'Lámina:5'],
  ['mortadela', 'Mortadela (ref. bologna)', 'embutidos', 'Bologna, beef and pork', 'Lámina:15'],
  ['pate', 'Paté', 'embutidos', 'Pate, liver', 'Cucharada:13'],
  ['prieta', 'Prieta (morcilla)', 'embutidos', 'Blood sausage', 'Trozo:80'],
  ['pepperoni', 'Pepperoni', 'embutidos', 'Pepperoni, beef and pork, sliced', 'Lámina:2'],

  // ── Pescados y mariscos ──
  ['salmon', 'Salmón al horno', 'pescados', 'Fish, salmon, Atlantic, farmed, cooked, dry heat', 'Filete:150'],
  ['salmon-crudo', 'Salmón crudo', 'pescados', 'Fish, salmon, Atlantic, farmed, raw', 'Filete:170'],
  ['salmon-ahumado', 'Salmón ahumado', 'pescados', 'Fish, salmon, chinook, smoked', 'Lámina:15'],
  ['salmon-lata', 'Salmón en conserva', 'pescados', 'Fish, salmon, pink, canned, drained solids', 'Porción:80'],
  ['atun-agua', 'Atún en agua', 'pescados', 'Fish, tuna, light, canned in water, drained solids', 'Lata drenada:120'],
  ['atun-aceite', 'Atún en aceite', 'pescados', 'Fish, tuna, light, canned in oil, drained solids', 'Lata drenada:120'],
  ['atun-fresco', 'Atún fresco a la plancha', 'pescados', 'Fish, tuna, fresh, yellowfin, cooked, dry heat', 'Filete:150'],
  ['jurel-lata', 'Jurel en conserva', 'pescados', 'Fish, mackerel, jack, canned, drained solids', 'Lata drenada:250|Porción:100'],
  ['jurel', 'Jurel fresco al horno', 'pescados', 'Fish, mackerel, Pacific and jack, mixed species, cooked, dry heat', 'Filete:150'],
  ['merluza', 'Merluza al horno (ref. whiting)', 'pescados', 'Fish, whiting, mixed species, cooked, dry heat', 'Filete:150'],
  ['merluza-cruda', 'Merluza cruda (ref. whiting)', 'pescados', 'Fish, whiting, mixed species, raw', 'Filete:170'],
  ['reineta', 'Reineta al horno (ref. butterfish)', 'pescados', 'Fish, butterfish, cooked, dry heat', 'Filete:150'],
  ['congrio', 'Congrio cocido (ref. cusk)', 'pescados', 'Fish, cusk, cooked, dry heat', 'Trozo:150'],
  ['corvina', 'Corvina cruda (ref. croaker)', 'pescados', 'Fish, croaker, Atlantic, raw', 'Filete:170'],
  ['tilapia', 'Tilapia al horno', 'pescados', 'Fish, tilapia, cooked, dry heat', 'Filete:150'],
  ['bacalao', 'Bacalao al horno', 'pescados', 'Fish, cod, Atlantic, cooked, dry heat', 'Filete:150'],
  ['sardinas-aceite', 'Sardinas en aceite', 'pescados', 'Fish, sardine, Atlantic, canned in oil, drained solids with bone', 'Lata drenada:90'],
  ['sardinas-tomate', 'Sardinas en salsa de tomate', 'pescados', 'Fish, sardine, Pacific, canned in tomato sauce, drained solids with bone', 'Lata:150'],
  ['trucha', 'Trucha al horno', 'pescados', 'Fish, trout, rainbow, farmed, cooked, dry heat', 'Filete:150'],
  ['lenguado', 'Lenguado al horno', 'pescados', 'Fish, flatfish (flounder and sole species), cooked, dry heat', 'Filete:150'],
  ['anchoas', 'Anchoas en aceite', 'pescados', 'Fish, anchovy, european, canned in oil, drained solids', 'Unidad:4'],
  ['camarones', 'Camarones cocidos', 'pescados', 'Crustaceans, shrimp, cooked', 'Porción:100'],
  ['choritos', 'Choritos cocidos', 'pescados', 'Mollusks, mussel, blue, cooked, moist heat', 'Porción:100'],
  ['almejas', 'Almejas o machas cocidas (ref. almeja)', 'pescados', 'Mollusks, clam, mixed species, cooked, moist heat', 'Porción:100'],
  ['jaiba', 'Jaiba o cangrejo cocido', 'pescados', 'Crustaceans, crab, blue, cooked, moist heat', 'Porción:100'],
  ['calamar-frito', 'Calamar frito', 'pescados', 'Mollusks, squid, mixed species, cooked, fried', 'Porción:100'],
  ['calamar', 'Calamar crudo', 'pescados', 'Mollusks, squid, mixed species, raw', 'Porción:100'],
  ['pulpo', 'Pulpo cocido', 'pescados', 'Mollusks, octopus, common, cooked, moist heat', 'Porción:100'],
  ['ostiones', 'Ostiones cocidos', 'pescados', 'Mollusks, scallop, (bay and sea), cooked, steamed', 'Porción:100'],
  ['kanikama', 'Kanikama (surimi)', 'pescados', 'Surimi', 'Barrita:17'],

  // ── Legumbres y soya ──
  ['porotos', 'Porotos cocidos', 'legumbres', 'Beans, kidney, all types, mature seeds, cooked, boiled, without salt', 'Taza:180'],
  ['porotos-crudos', 'Porotos crudos (secos)', 'legumbres', 'Beans, kidney, all types, mature seeds, raw', 'Taza:185'],
  ['porotos-negros', 'Porotos negros cocidos', 'legumbres', 'Beans, black, mature seeds, cooked, boiled, without salt', 'Taza:172'],
  ['porotos-blancos', 'Porotos blancos cocidos', 'legumbres', 'Beans, white, mature seeds, cooked, boiled, without salt', 'Taza:179'],
  ['porotos-granados', 'Porotos granados cocidos (ref. cranberry)', 'legumbres', 'Beans, cranberry (roman), mature seeds, cooked, boiled, without salt', 'Taza:177'],
  ['lentejas', 'Lentejas cocidas', 'legumbres', 'Lentils, mature seeds, cooked, boiled, without salt', 'Taza:198'],
  ['lentejas-crudas', 'Lentejas crudas', 'legumbres', 'Lentils, raw', 'Taza:192'],
  ['garbanzos', 'Garbanzos cocidos', 'legumbres', 'Chickpeas (garbanzo beans, bengal gram), mature seeds, cooked, boiled, without salt', 'Taza:164'],
  ['garbanzos-crudos', 'Garbanzos crudos', 'legumbres', 'Chickpeas (garbanzo beans, bengal gram), mature seeds, raw', 'Taza:200'],
  ['arvejas-partidas', 'Arvejas partidas cocidas', 'legumbres', 'Peas, split, mature seeds, cooked, boiled, without salt', 'Taza:196'],
  ['habas', 'Habas cocidas', 'legumbres', 'Broadbeans (fava beans), mature seeds, cooked, boiled, without salt', 'Taza:170'],
  ['soya', 'Porotos de soya cocidos', 'legumbres', 'Soybeans, mature cooked, boiled, without salt', 'Taza:172'],
  ['tofu', 'Tofu firme', 'legumbres', 'Tofu, raw, firm, prepared with calcium sulfate', 'Porción:100'],
  ['hummus', 'Hummus', 'legumbres', 'Hummus, commercial', 'Cucharada:15'],
  ['edamame', 'Edamame', 'legumbres', 'Edamame, frozen, prepared', 'Taza:155'],
  ['mani', 'Maní tostado sin sal', 'frutos_secos', 'Peanuts, all types, dry-roasted, without salt', 'Puñado:28'],
  ['mani-salado', 'Maní salado', 'frutos_secos', 'Peanuts, all types, dry-roasted, with salt', 'Puñado:28'],
  ['mantequilla-mani', 'Mantequilla de maní', 'frutos_secos', 'Peanut butter, smooth style, with salt', 'Cucharada:16'],

  // ── Cereales, arroz y pastas ──
  ['arroz', 'Arroz blanco cocido', 'cereales', 'Rice, white, long-grain, regular, enriched, cooked', 'Taza:160|Porción:150'],
  ['arroz-crudo', 'Arroz blanco crudo', 'cereales', 'Rice, white, long-grain, regular, raw, enriched', 'Taza:185|Porción (60 g):60'],
  ['arroz-integral', 'Arroz integral cocido', 'cereales', 'Rice, brown, long-grain, cooked', 'Taza:195'],
  ['arroz-integral-crudo', 'Arroz integral crudo', 'cereales', 'Rice, brown, long-grain, raw', 'Porción (60 g):60'],
  ['fideos', 'Fideos o tallarines cocidos', 'cereales', 'Pasta, cooked, enriched, without added salt', 'Taza:140|Plato:250'],
  ['fideos-crudos', 'Fideos o tallarines crudos', 'cereales', 'Pasta, dry, enriched', 'Porción (80 g):80'],
  ['fideos-integrales', 'Fideos integrales cocidos', 'cereales', 'Pasta, whole-wheat, cooked', 'Taza:140'],
  ['fideos-arroz', 'Fideos de arroz cocidos', 'cereales', 'Rice noodles, cooked', 'Taza:176'],
  ['avena', 'Avena', 'cereales', 'Cereals, oats, regular and quick, not fortified, dry', 'Taza:80|Cucharada:10|Porción (40 g):40'],
  ['avena-cocida', 'Avena cocida en agua', 'cereales', 'Cereals, oats, regular and quick, unenriched, cooked with water', 'Taza:234'],
  ['quinoa', 'Quínoa cocida', 'cereales', 'Quinoa, cooked', 'Taza:185'],
  ['quinoa-cruda', 'Quínoa cruda', 'cereales', 'Quinoa, uncooked', 'Porción (60 g):60'],
  ['mote-trigo', 'Mote de trigo cocido (ref. bulgur)', 'cereales', 'Bulgur, cooked', 'Taza:182'],
  ['mote-maiz', 'Mote de maíz (ref. hominy)', 'cereales', 'Hominy, canned, white', 'Taza:165'],
  ['cuscus', 'Cuscús cocido', 'cereales', 'Couscous, cooked', 'Taza:157'],
  ['harina', 'Harina de trigo', 'cereales', 'Wheat flour, white, all-purpose, enriched, bleached', 'Taza:125|Cucharada:8'],
  ['harina-integral', 'Harina integral', 'cereales', 'Wheat flour, whole-grain', 'Taza:120|Cucharada:8'],
  ['harina-tostada', 'Harina tostada (ref. harina integral)', 'cereales', 'Wheat flour, whole-grain', 'Cucharada:8'],
  ['maicena', 'Maicena', 'cereales', 'Cornstarch', 'Cucharada:8'],
  ['semola', 'Sémola', 'cereales', 'Semolina, enriched', 'Cucharada:10'],
  ['polenta', 'Polenta (harina de maíz)', 'cereales', 'Cornmeal, whole-grain, yellow', 'Taza:120'],
  ['granola', 'Granola', 'cereales', 'Cereals ready-to-eat, granola, homemade', 'Taza:120|Porción (40 g):40'],
  ['cereal-maiz', 'Cereal de maíz (tipo corn flakes)', 'cereales', 'corn flakes', 'Taza:28'],
  ['arroz-inflado', 'Arroz inflado', 'cereales', 'Cereals ready-to-eat, rice, puffed, fortified', 'Taza:14'],
  ['salvado', 'Salvado de trigo', 'cereales', 'Wheat bran, crude', 'Cucharada:4'],
  ['germen-trigo', 'Germen de trigo', 'cereales', 'Wheat germ, crude', 'Cucharada:7'],
  ['galletas-arroz', 'Galletas de arroz', 'cereales', 'Snacks, rice cakes, brown rice, plain', 'Unidad:9'],
  ['tortilla-trigo', 'Tortilla de trigo', 'cereales', 'Tortillas, ready-to-bake or -fry, flour', 'Unidad:45'],
  ['tortilla-maiz', 'Tortilla de maíz', 'cereales', 'Tortillas, ready-to-bake or -fry, corn', 'Unidad:26'],
  ['pan-rallado', 'Pan rallado', 'cereales', 'Bread, crumbs, dry, grated, plain', 'Cucharada:7'],

  // ── Panes y masas ──
  ['pan-molde', 'Pan de molde blanco', 'panes', 'Bread, white, commercially prepared (includes soft bread crumbs)', 'Rebanada:25'],
  ['pan-integral', 'Pan de molde integral', 'panes', 'Bread, whole-wheat, commercially prepared', 'Rebanada:28'],
  ['pan-centeno', 'Pan de centeno', 'panes', 'Bread, rye', 'Rebanada:32'],
  ['pan-multigrano', 'Pan multigrano', 'panes', 'Bread, multi-grain (includes whole-grain)', 'Rebanada:26'],
  ['pan-pita', 'Pan pita', 'panes', 'Bread, pita, white, enriched', 'Unidad:60'],
  ['pan-pita-integral', 'Pan pita integral', 'panes', 'Bread, pita, whole-wheat', 'Unidad:64'],
  ['pan-completo', 'Pan de completo o hamburguesa', 'panes', 'Rolls, hamburger or hotdog, plain', 'Unidad:60'],
  ['baguette', 'Baguette o pan francés', 'panes', 'Bread, french or vienna (includes sourdough)', 'Rebanada:25'],
  ['croissant', 'Croissant (medialuna)', 'panes', 'Croissants, butter', 'Unidad:57'],
  ['bagel', 'Bagel', 'panes', 'Bagels, plain, enriched, with calcium propionate', 'Unidad:100'],
  ['queque', 'Queque', 'panes', 'Cake, pound, commercially prepared, butter', 'Trozo:50'],
  ['galletas-soda', 'Galletas de agua o soda', 'panes', 'Crackers, saltines (includes oyster, soda, soup)', 'Unidad:3|Paquete individual:25'],
  ['galletas-integrales', 'Galletas integrales', 'panes', 'Crackers, whole-wheat', 'Unidad:4'],
  ['galletas-dulces', 'Galletas dulces tipo María', 'panes', 'Cookies, butter, commercially prepared', 'Unidad:6'],
  ['galletas-chips', 'Galletas con chips de chocolate', 'panes', 'Cookies, chocolate chip, commercially prepared, regular', 'Unidad:10'],
  ['galletas-rellenas', 'Galletas rellenas de chocolate', 'panes', 'Cookies, chocolate sandwich, with creme filling, regular', 'Unidad:12'],
  ['muffin', 'Muffin', 'panes', 'Muffins, blueberry, commercially prepared', 'Unidad:110'],
  ['kuchen', 'Kuchen de manzana (ref. pie de manzana)', 'panes', 'Pie, apple, commercially prepared, enriched flour', 'Trozo:120'],
  ['torta-chocolate', 'Torta de chocolate', 'panes', 'Cake, chocolate, commercially prepared with chocolate frosting', 'Trozo:90'],
  ['donut', 'Donut', 'panes', 'Doughnuts, cake-type, plain', 'Unidad:47'],

  // ── Verduras ──
  ['tomate', 'Tomate', 'verduras', 'Tomatoes, red, ripe, raw, year round average', 'Unidad mediana:120'],
  ['lechuga', 'Lechuga', 'verduras', 'Lettuce, green leaf, raw', 'Taza:36|Plato:80'],
  ['lechuga-escarola', 'Lechuga escarola (iceberg)', 'verduras', 'Lettuce, iceberg (includes crisphead types), raw', 'Taza:72'],
  ['lechuga-romana', 'Lechuga romana', 'verduras', 'Lettuce, cos or romaine, raw', 'Taza:47'],
  ['cebolla', 'Cebolla', 'verduras', 'Onions, raw', 'Unidad mediana:110|Taza picada:160'],
  ['cebolla-cocida', 'Cebolla cocida', 'verduras', 'Onions, cooked, boiled, drained, without salt', 'Taza:210'],
  ['cebollin', 'Cebollín', 'verduras', 'Onions, spring or scallions (includes tops and bulb), raw', 'Unidad:15'],
  ['zanahoria', 'Zanahoria', 'verduras', 'Carrots, raw', 'Unidad mediana:60|Taza rallada:110'],
  ['zanahoria-cocida', 'Zanahoria cocida', 'verduras', 'Carrots, cooked, boiled, drained, without salt', 'Taza:156'],
  ['zapallo', 'Zapallo (ref. calabaza)', 'verduras', 'Pumpkin, raw', 'Trozo:150'],
  ['zapallo-cocido', 'Zapallo cocido', 'verduras', 'Pumpkin, cooked, boiled, drained, without salt', 'Taza:245'],
  ['zapallo-italiano', 'Zapallo italiano', 'verduras', 'Squash, summer, zucchini, includes skin, raw', 'Unidad:200'],
  ['zapallo-italiano-cocido', 'Zapallo italiano cocido', 'verduras', 'Squash, summer, zucchini, includes skin, cooked, boiled, drained, without salt', 'Taza:180'],
  ['zapallo-camote', 'Zapallo camote (butternut) al horno', 'verduras', 'Squash, winter, butternut, cooked, baked, without salt', 'Taza:205'],
  ['papa', 'Papa cruda', 'verduras', 'Potatoes, flesh and skin, raw', 'Unidad mediana:170'],
  ['papa-cocida', 'Papa cocida', 'verduras', 'Potatoes, boiled, cooked in skin, flesh, without salt', 'Unidad mediana:150'],
  ['papa-horno', 'Papa al horno con cáscara', 'verduras', 'Potatoes, baked, flesh and skin, without salt', 'Unidad mediana:170'],
  ['papas-fritas', 'Papas fritas', 'verduras', 'Fast foods, potato, french fried in vegetable oil', 'Porción chica:70|Porción mediana:120|Porción grande:160'],
  ['pure-papas', 'Puré de papas', 'verduras', 'Potatoes, mashed, home-prepared, whole milk and butter added', 'Taza:210'],
  ['camote', 'Camote al horno', 'verduras', 'Sweet potato, cooked, baked in skin, flesh, without salt', 'Unidad:150'],
  ['choclo', 'Choclo cocido', 'verduras', 'Corn, sweet, yellow, cooked, boiled, drained, without salt', 'Taza:165|Unidad (granos):100'],
  ['choclo-crudo', 'Choclo crudo (granos)', 'verduras', 'Corn, sweet, yellow, raw', 'Taza:145'],
  ['choclo-conserva', 'Choclo en conserva', 'verduras', 'Corn, sweet, yellow, canned, whole kernel, drained solids', 'Taza:165'],
  ['brocoli', 'Brócoli crudo', 'verduras', 'Broccoli, raw', 'Taza:90'],
  ['brocoli-cocido', 'Brócoli cocido', 'verduras', 'Broccoli, cooked, boiled, drained, without salt', 'Taza:156'],
  ['coliflor', 'Coliflor cruda', 'verduras', 'Cauliflower, raw', 'Taza:107'],
  ['coliflor-cocida', 'Coliflor cocida', 'verduras', 'Cauliflower, cooked, boiled, drained, without salt', 'Taza:124'],
  ['repollo', 'Repollo', 'verduras', 'Cabbage, raw', 'Taza:89'],
  ['repollo-morado', 'Repollo morado', 'verduras', 'Cabbage, red, raw', 'Taza:89'],
  ['espinaca', 'Espinaca cruda', 'verduras', 'Spinach, raw', 'Taza:30'],
  ['espinaca-cocida', 'Espinaca cocida', 'verduras', 'Spinach, cooked, boiled, drained, without salt', 'Taza:180'],
  ['acelga', 'Acelga cruda', 'verduras', 'Chard, swiss, raw', 'Taza:36'],
  ['acelga-cocida', 'Acelga cocida', 'verduras', 'Chard, swiss, cooked, boiled, drained, without salt', 'Taza:175'],
  ['pepino', 'Pepino', 'verduras', 'Cucumber, with peel, raw', 'Unidad:300|Taza:120'],
  ['pimenton-rojo', 'Pimentón rojo', 'verduras', 'Peppers, sweet, red, raw', 'Unidad:150'],
  ['pimenton-verde', 'Pimentón verde', 'verduras', 'Peppers, sweet, green, raw', 'Unidad:150'],
  ['pimenton-amarillo', 'Pimentón amarillo', 'verduras', 'Peppers, sweet, yellow, raw', 'Unidad:180'],
  ['aji-verde', 'Ají verde', 'verduras', 'Peppers, hot chili, green, raw', 'Unidad:45'],
  ['ajo', 'Ajo', 'verduras', 'Garlic, raw', 'Diente:3'],
  ['champinones', 'Champiñones', 'verduras', 'Mushrooms, white, raw', 'Taza:70'],
  ['champinones-cocidos', 'Champiñones cocidos', 'verduras', 'Mushrooms, white, cooked, boiled, drained, without salt', 'Taza:156'],
  ['porotos-verdes', 'Porotos verdes cocidos', 'verduras', 'Beans, snap, green, cooked, boiled, drained, without salt', 'Taza:125'],
  ['porotos-verdes-crudos', 'Porotos verdes crudos', 'verduras', 'Beans, snap, green, raw', 'Taza:100'],
  ['arvejas', 'Arvejas cocidas', 'verduras', 'Peas, green, frozen, cooked, boiled, drained, without salt', 'Taza:160'],
  ['arvejas-crudas', 'Arvejas crudas', 'verduras', 'Peas, green, raw', 'Taza:145'],
  ['betarraga', 'Betarraga cocida', 'verduras', 'Beets, cooked, boiled, drained', 'Unidad:100|Taza:170'],
  ['betarraga-cruda', 'Betarraga cruda', 'verduras', 'Beets, raw', 'Taza:136'],
  ['apio', 'Apio', 'verduras', 'Celery, raw', 'Tallo:40'],
  ['esparragos', 'Espárragos cocidos', 'verduras', 'Asparagus, cooked, boiled, drained', 'Unidad:15'],
  ['berenjena', 'Berenjena', 'verduras', 'Eggplant, raw', 'Unidad:450'],
  ['berenjena-cocida', 'Berenjena cocida', 'verduras', 'Eggplant, cooked, boiled, drained, without salt', 'Taza:99'],
  ['palta', 'Palta hass', 'verduras', 'Avocados, raw, California', 'Unidad:170|Media unidad:85|Cucharada:15'],
  ['palta-comun', 'Palta (otras variedades)', 'verduras', 'Avocados, raw, all commercial varieties', 'Unidad:200|Cucharada:15'],
  ['rabanitos', 'Rabanitos', 'verduras', 'Radishes, raw', 'Unidad:5'],
  ['alcachofa', 'Alcachofa cocida', 'verduras', 'Artichokes, (globe or french), cooked, boiled, drained, without salt', 'Unidad:120'],
  ['kale', 'Kale', 'verduras', 'Kale, raw', 'Taza:21'],
  ['rucula', 'Rúcula', 'verduras', 'Arugula, raw', 'Taza:20'],
  ['brotes-soya', 'Brotes de soya', 'verduras', 'Mung beans, mature seeds, sprouted, raw', 'Taza:104'],
  ['cilantro', 'Cilantro', 'verduras', 'Coriander (cilantro) leaves, raw', 'Cucharada:1'],
  ['perejil', 'Perejil', 'verduras', 'Parsley, fresh', 'Cucharada:4'],
  ['albahaca', 'Albahaca', 'verduras', 'Basil, fresh', 'Cucharada:3'],
  ['puerro', 'Puerro', 'verduras', 'Leeks, (bulb and lower leaf-portion), raw', 'Unidad:90'],
  ['nabo', 'Nabo', 'verduras', 'Turnips, raw', 'Unidad:120'],
  ['tomate-conserva', 'Tomate en conserva', 'verduras', 'Tomatoes, red, ripe, canned, packed in tomato juice', 'Taza:240'],
  ['salsa-tomate', 'Salsa de tomate natural', 'verduras', 'Tomato products, canned, sauce', 'Cucharada:15|Taza:245'],
  ['pasta-tomate', 'Pasta de tomate (concentrado)', 'verduras', 'Tomato products, canned, paste', 'Cucharada:16'],
  ['pepinillos', 'Pepinillos en vinagre', 'verduras', 'Pickles, cucumber, dill or kosher dill', 'Unidad:35'],
  ['aceitunas', 'Aceitunas negras', 'verduras', 'Olives, ripe, canned (small-extra large)', 'Unidad:4'],
  ['aceitunas-verdes', 'Aceitunas verdes', 'verduras', 'Olives, pickled, canned or bottled, green', 'Unidad:3'],
  ['cochayuyo', 'Cochayuyo (ref. alga kelp)', 'verduras', 'Seaweed, kelp, raw', 'Taza:80'],
  ['verduras-mix', 'Mix de verduras congeladas cocidas', 'verduras', 'Vegetables, mixed, frozen, cooked, boiled, drained, without salt', 'Taza:182'],

  // ── Frutas ──
  ['platano', 'Plátano', 'frutas', 'Bananas, raw', 'Unidad mediana:120|Unidad grande:140'],
  ['manzana', 'Manzana', 'frutas', 'Apples, raw, with skin', 'Unidad mediana:180'],
  ['manzana-pelada', 'Manzana sin cáscara', 'frutas', 'Apples, raw, without skin', 'Unidad mediana:160'],
  ['pera', 'Pera', 'frutas', 'Pears, raw', 'Unidad mediana:180'],
  ['naranja', 'Naranja', 'frutas', 'Oranges, raw, all commercial varieties', 'Unidad mediana:140'],
  ['mandarina', 'Mandarina', 'frutas', 'Tangerines, (mandarin oranges), raw', 'Unidad:88'],
  ['limon', 'Limón', 'frutas', 'Lemons, raw, without peel', 'Unidad:60'],
  ['jugo-limon', 'Jugo de limón', 'frutas', 'Lemon juice, raw', 'Cucharada:15'],
  ['uvas', 'Uvas', 'frutas', 'Grapes, red or green (European type, such as Thompson seedless), raw', 'Taza:150|Racimo chico:100'],
  ['frutillas', 'Frutillas', 'frutas', 'Strawberries, raw', 'Taza:150|Unidad:12'],
  ['arandanos', 'Arándanos', 'frutas', 'Blueberries, raw', 'Taza:148'],
  ['frambuesas', 'Frambuesas', 'frutas', 'Raspberries, raw', 'Taza:123'],
  ['moras', 'Moras', 'frutas', 'Blackberries, raw', 'Taza:144'],
  ['kiwi', 'Kiwi', 'frutas', 'Kiwifruit, green, raw', 'Unidad:75'],
  ['pina', 'Piña', 'frutas', 'Pineapple, raw, all varieties', 'Rodaja:85|Taza:165'],
  ['mango', 'Mango', 'frutas', 'Mangos, raw', 'Unidad:330|Taza:165'],
  ['papaya', 'Papaya', 'frutas', 'Papayas, raw', 'Taza:145'],
  ['sandia', 'Sandía', 'frutas', 'Watermelon, raw', 'Tajada:280|Taza:152'],
  ['melon-tuna', 'Melón tuna', 'frutas', 'Melons, honeydew, raw', 'Tajada:125|Taza:170'],
  ['melon-calameno', 'Melón calameño (ref. cantaloupe)', 'frutas', 'Melons, cantaloupe, raw', 'Tajada:100|Taza:160'],
  ['durazno', 'Durazno', 'frutas', 'Peaches, yellow, raw', 'Unidad:150'],
  ['damasco', 'Damasco', 'frutas', 'Apricots, raw', 'Unidad:35'],
  ['ciruela', 'Ciruela', 'frutas', 'Plums, raw', 'Unidad:66'],
  ['cereza', 'Cerezas', 'frutas', 'Cherries, sweet, raw', 'Taza:138|Unidad:8'],
  ['chirimoya', 'Chirimoya', 'frutas', 'Cherimoya, raw', 'Unidad:235|Taza:160'],
  ['tuna', 'Tuna', 'frutas', 'Prickly pears, raw', 'Unidad:103'],
  ['granada', 'Granada', 'frutas', 'Pomegranates, raw', 'Unidad:280'],
  ['membrillo', 'Membrillo', 'frutas', 'Quinces, raw', 'Unidad:90'],
  ['higo', 'Higo', 'frutas', 'Figs, raw', 'Unidad:50'],
  ['higos-secos', 'Higos secos', 'frutas', 'Figs, dried, uncooked', 'Unidad:8'],
  ['pasas', 'Pasas', 'frutas', 'Raisins, seedless', 'Cucharada:9|Puñado:30'],
  ['ciruelas-secas', 'Ciruelas secas', 'frutas', 'Plums, dried (prunes), uncooked', 'Unidad:10'],
  ['datiles', 'Dátiles', 'frutas', 'Dates, medjool', 'Unidad:24'],
  ['damascos-secos', 'Descarozados o damascos secos', 'frutas', 'Apricots, dried, sulfured, uncooked', 'Unidad:7'],
  ['huesillos', 'Huesillos (ref. durazno deshidratado)', 'frutas', 'Peaches, dried, sulfured, uncooked', 'Unidad:13'],
  ['coco-rallado', 'Coco rallado', 'frutas', 'Nuts, coconut meat, dried (desiccated), not sweetened', 'Cucharada:5'],
  ['pomelo', 'Pomelo', 'frutas', 'Grapefruit, raw, pink and red, all areas', 'Media unidad:120'],
  ['maracuya', 'Maracuyá', 'frutas', 'Passion-fruit, (granadilla), purple, raw', 'Unidad:18'],
  ['durazno-almibar', 'Duraznos en almíbar', 'frutas', 'Peaches, canned, heavy syrup pack, solids and liquids', 'Mitad:80'],
  ['arandano-seco', 'Cranberries deshidratados', 'frutas', 'Cranberries, dried, sweetened', 'Cucharada:10'],
  ['jugo-naranja', 'Jugo de naranja natural', 'bebidas', 'Orange juice, raw', 'Vaso:200'],
  ['jugo-naranja-caja', 'Jugo de naranja envasado', 'bebidas', 'Orange juice, chilled, includes from concentrate', 'Vaso:200'],
  ['jugo-manzana', 'Jugo de manzana', 'bebidas', 'Apple juice, canned or bottled, unsweetened, without added ascorbic acid', 'Vaso:200'],
  ['nectar-durazno', 'Néctar de durazno', 'bebidas', 'Peach nectar, canned, without added ascorbic acid', 'Vaso:200'],
  ['agua-coco', 'Agua de coco', 'bebidas', 'Nuts, coconut water (liquid from coconuts)', 'Vaso:240'],

  // ── Frutos secos y semillas ──
  ['almendras', 'Almendras', 'frutos_secos', 'Nuts, almonds', 'Unidad:1.2|Puñado:28'],
  ['nueces', 'Nueces', 'frutos_secos', 'Nuts, walnuts, english', 'Mitad:2|Puñado:28'],
  ['cajuiles', 'Castañas de cajú', 'frutos_secos', 'Nuts, cashew nuts, dry roasted, without salt added', 'Puñado:28'],
  ['pistachos', 'Pistachos', 'frutos_secos', 'Nuts, pistachio nuts, dry roasted, without salt added', 'Puñado:28'],
  ['avellanas', 'Avellanas', 'frutos_secos', 'Nuts, hazelnuts or filberts', 'Puñado:28'],
  ['castanas', 'Castañas asadas', 'frutos_secos', 'Nuts, chestnuts, european, roasted', 'Unidad:8'],
  ['nueces-brasil', 'Nueces de Brasil', 'frutos_secos', 'Nuts, brazilnuts, dried, unblanched', 'Unidad:5'],
  ['chia', 'Semillas de chía', 'frutos_secos', 'Seeds, chia seeds, dried', 'Cucharada:12'],
  ['linaza', 'Linaza', 'frutos_secos', 'Seeds, flaxseed', 'Cucharada:10'],
  ['semillas-maravilla', 'Semillas de maravilla', 'frutos_secos', 'Seeds, sunflower seed kernels, dried', 'Cucharada:9'],
  ['semillas-zapallo', 'Semillas de zapallo', 'frutos_secos', 'Seeds, pumpkin and squash seed kernels, dried', 'Cucharada:9'],
  ['sesamo', 'Sésamo', 'frutos_secos', 'Seeds, sesame seeds, whole, dried', 'Cucharada:9'],
  ['mix-frutos-secos', 'Mix de frutos secos', 'frutos_secos', 'Nuts, mixed nuts, dry roasted, with peanuts, without salt added', 'Puñado:28'],
  ['mantequilla-almendra', 'Mantequilla de almendras', 'frutos_secos', 'Nuts, almond butter, plain, without salt added', 'Cucharada:16'],

  // ── Dulces y postres ──
  ['azucar', 'Azúcar', 'dulces', 'Sugars, granulated', 'Cucharadita:5|Cucharada:12'],
  ['azucar-flor', 'Azúcar flor', 'dulces', 'Sugars, powdered', 'Cucharada:8'],
  ['azucar-rubia', 'Azúcar rubia', 'dulces', 'Sugars, brown', 'Cucharadita:5'],
  ['miel', 'Miel', 'dulces', 'Honey', 'Cucharadita:7|Cucharada:21'],
  ['manjar', 'Manjar (dulce de leche)', 'dulces', 'Dulce de Leche', 'Cucharadita:7|Cucharada:19'],
  ['mermelada', 'Mermelada', 'dulces', 'Jams and preserves', 'Cucharadita:7|Cucharada:20'],
  ['mermelada-light', 'Mermelada sin azúcar', 'dulces', 'Jams and preserves, no sugar', 'Cucharada:14'],
  ['chocolate-leche', 'Chocolate de leche', 'dulces', 'Candies, milk chocolate', 'Cuadrito:5|Barra:30'],
  ['chocolate-amargo', 'Chocolate amargo 70–85 %', 'dulces', 'Chocolate, dark, 70-85% cacao solids', 'Cuadrito:5|Porción:30'],
  ['chocolate-semiamargo', 'Chocolate semiamargo', 'dulces', 'Candies, semisweet chocolate', 'Cuadrito:5'],
  ['cacao', 'Cacao en polvo sin azúcar', 'dulces', 'Cocoa, dry powder, unsweetened', 'Cucharada:5'],
  ['helado-vainilla', 'Helado de vainilla', 'dulces', 'Ice creams, vanilla', 'Bola:66|Taza:132'],
  ['helado-chocolate', 'Helado de chocolate', 'dulces', 'Ice creams, chocolate', 'Bola:66'],
  ['helado-agua', 'Helado de agua', 'dulces', 'Frozen novelties, ice type, pop', 'Unidad:60'],
  ['gelatina', 'Gelatina preparada', 'dulces', 'Gelatin desserts, dry mix, prepared with water', 'Pote:120'],
  ['flan', 'Flan de caramelo', 'dulces', 'flan, caramel custard, prepared-from-recipe', 'Porción:120'],
  ['arroz-con-leche', 'Arroz con leche', 'dulces', 'Puddings, rice, ready-to-eat', 'Pote:120'],
  ['caramelos', 'Caramelos', 'dulces', 'Candies, hard', 'Unidad:5'],
  ['gomitas', 'Gomitas', 'dulces', 'Candies, gumdrops, starch jelly pieces', 'Unidad:4'],
  ['barra-cereal', 'Barra de cereal', 'dulces', 'Snacks, granola bars, soft, uncoated, plain', 'Unidad:28'],
  ['crema-chantilly', 'Crema chantilly en spray', 'dulces', 'Cream, whipped, cream topping, pressurized', 'Porción:10'],
  ['crema-avellanas', 'Crema de avellanas y cacao', 'dulces', 'Chocolate-flavored hazelnut spread', 'Cucharada:19'],

  // ── Bebidas ──
  ['agua', 'Agua', 'bebidas', 'Beverages, water, tap, drinking', 'Vaso:250'],
  ['cafe', 'Café de grano preparado', 'bebidas', 'Beverages, coffee, brewed, prepared with tap water', 'Taza:240'],
  ['cafe-instantaneo', 'Café instantáneo preparado', 'bebidas', 'Beverages, coffee, instant, regular, prepared with water', 'Taza:240'],
  ['te', 'Té negro', 'bebidas', 'Beverages, tea, black, brewed, prepared with tap water', 'Taza:240'],
  ['te-hierbas', 'Agua de hierbas', 'bebidas', 'Beverages, tea, herb, other than chamomile, brewed', 'Taza:240'],
  ['bebida-cola', 'Bebida cola', 'bebidas', 'Beverages, carbonated, cola, regular', 'Lata:350|Vaso:250'],
  ['bebida-light', 'Bebida cola light o zero', 'bebidas', 'Beverages, carbonated, low calorie, cola or pepper-type, with aspartame, contains caffeine', 'Lata:350|Vaso:250'],
  ['bebida-naranja', 'Bebida de naranja', 'bebidas', 'Beverages, carbonated, orange', 'Lata:350'],
  ['agua-tonica', 'Agua tónica', 'bebidas', 'Beverages, carbonated, tonic water', 'Vaso:250'],
  ['energetica', 'Bebida energética', 'bebidas', 'energy drink', 'Lata:250'],
  ['cerveza', 'Cerveza', 'bebidas', 'Alcoholic beverage, beer, regular, all', 'Lata:350|Schop:500'],
  ['cerveza-light', 'Cerveza light', 'bebidas', 'Alcoholic beverage, beer, light', 'Lata:350'],
  ['vino-tinto', 'Vino tinto', 'bebidas', 'Alcoholic beverage, wine, table, red', 'Copa:150'],
  ['vino-blanco', 'Vino blanco', 'bebidas', 'Alcoholic beverage, wine, table, white', 'Copa:150'],
  ['pisco', 'Pisco o destilado 40°', 'bebidas', 'Alcoholic beverage, distilled, all (gin, rum, vodka, whiskey) 80 proof', 'Corrido (45 ml):42'],

  // ── Snacks ──
  ['papas-bolsa', 'Papas fritas de bolsa', 'snacks', 'Snacks, potato chips, plain, salted', 'Bolsa chica:40|Puñado:15'],
  ['ramitas', 'Ramitas o pretzels', 'snacks', 'Snacks, pretzels, hard, plain, salted', 'Puñado:30'],
  ['cabritas', 'Cabritas (sin aceite)', 'snacks', 'Snacks, popcorn, air-popped', 'Taza:8'],
  ['cabritas-micro', 'Cabritas de microondas', 'snacks', 'popcorn, microwave, regular', 'Taza:11|Bolsa:85'],
  ['nachos', 'Nachos (tortilla chips)', 'snacks', 'Snacks, tortilla chips, plain', 'Puñado:28'],

  // ── Salsas y condimentos ──
  ['ketchup', 'Ketchup', 'salsas', 'Catsup', 'Cucharada:17|Sobre:9'],
  ['mostaza', 'Mostaza', 'salsas', 'Mustard, prepared, yellow', 'Cucharadita:5'],
  ['salsa-soya', 'Salsa de soya', 'salsas', 'Soy sauce made from soy and wheat (shoyu)', 'Cucharada:16'],
  ['salsa-pasta', 'Salsa de tomate para pastas', 'salsas', 'Sauce, pasta, spaghetti/marinara, ready-to-serve', 'Taza:250'],
  ['pesto', 'Pesto', 'salsas', 'pesto', 'Cucharada:16'],
  ['vinagre', 'Vinagre', 'salsas', 'Vinegar, distilled', 'Cucharada:15'],
  ['aceto', 'Aceto balsámico', 'salsas', 'Vinegar, balsamic', 'Cucharada:16'],
  ['sal', 'Sal', 'salsas', 'Salt, table', 'Cucharadita:6|Pizca:0.4'],
  ['merken', 'Merkén (ref. ají en polvo)', 'salsas', 'Spices, chili powder', 'Cucharadita:3'],
  ['pimienta', 'Pimienta negra', 'salsas', 'Spices, pepper, black', 'Cucharadita:2'],
  ['oregano', 'Orégano', 'salsas', 'Spices, oregano, dried', 'Cucharadita:1'],
  ['comino', 'Comino', 'salsas', 'Spices, cumin seed', 'Cucharadita:2'],
  ['salsa-bbq', 'Salsa barbecue', 'salsas', 'Sauce, barbecue', 'Cucharada:17'],
  ['salsa-cesar', 'Aderezo césar', 'salsas', 'Salad dressing, caesar dressing, regular', 'Cucharada:15'],
  ['salsa-aji', 'Salsa de ají picante', 'salsas', 'Sauce, ready-to-serve, pepper or hot', 'Cucharadita:5'],
  ['caldo-cubo', 'Caldo en cubo (gallina)', 'salsas', 'Soup, chicken broth or bouillon, dry', 'Cubo:5'],
  ['levadura', 'Levadura seca', 'salsas', "Leavening agents, yeast, baker's, active dry", 'Sobre:7'],
  ['polvos-hornear', 'Polvos de hornear', 'salsas', 'Leavening agents, baking powder, double-acting, sodium aluminum sulfate', 'Cucharadita:5'],
  ['gelatina-sin-sabor', 'Gelatina sin sabor', 'salsas', 'Gelatins, dry powder, unsweetened', 'Sobre:7'],

  // ── Suplementos ──
  ['whey', 'Proteína whey (polvo)', 'suplementos', 'Protein powder whey based', 'Scoop:30'],
  ['proteina-soya', 'Proteína de soya aislada', 'suplementos', 'Soy protein isolate', 'Scoop:30'],

  // ── Comida rápida ──
  ['hamburguesa', 'Hamburguesa simple', 'comida_rapida', 'Fast foods, hamburger; single, regular patty; plain', 'Unidad:90'],
  ['pizza', 'Pizza de queso', 'comida_rapida', 'Pizza, cheese topping, regular crust', 'Trozo:107'],
  ['pollo-frito', 'Pollo frito apanado', 'comida_rapida', 'Fried chicken, breast, meat and skin and breading', 'Presa:160'],
  ['lasana', 'Lasaña de carne', 'comida_rapida', 'Lasagna with meat sauce, frozen, prepared', 'Porción:250'],
];

// Alimentos sin equivalente en USDA: valores por 100 g (kcal, proteína, carbohidratos, grasa, fibra).
export const CUSTOM = [
  ['creatina', 'Creatina monohidrato', 'suplementos', [0, 0, 0, 0, 0], 'Medida:5'],
  ['isotonica', 'Bebida isotónica', 'bebidas', [24, 0, 6, 0, 0], 'Botella:500'],
  ['cafe-cortado', 'Café cortado (con 30 ml de leche entera)', 'bebidas', [9, 0.6, 0.8, 0.5, 0], 'Taza:150'],
];

// Preparaciones: [id, nombre, porción "Nombre:g", rendimiento (peso final / peso de ingredientes), ingredientes "id:g, id:g"]
export const RECIPES = [
  ['cazuela-vacuno', 'Cazuela de vacuno', 'Plato:450', 0.85, 'osobuco-crudo:500, papa:600, zapallo:400, choclo-crudo:300, porotos-verdes-crudos:150, arroz-crudo:60, zanahoria:100, cebolla:100, pimenton-rojo:60, agua:1500'],
  ['cazuela-ave', 'Cazuela de ave', 'Plato:450', 0.85, 'trutro-crudo:600, papa:600, zapallo:400, choclo-crudo:300, porotos-verdes-crudos:150, arroz-crudo:60, zanahoria:100, cebolla:100, agua:1500'],
  ['porotos-riendas', 'Porotos con riendas', 'Plato:350', 0.8, 'porotos-crudos:250, fideos-crudos:100, zapallo:250, cebolla:100, zanahoria:50, aceite-maravilla:20, agua:1500'],
  ['porotos-granados-prep', 'Porotos granados', 'Plato:350', 0.9, 'porotos-granados:600, choclo-crudo:300, zapallo:300, cebolla:100, albahaca:5, aceite-maravilla:20, agua:500'],
  ['pastel-choclo', 'Pastel de choclo', 'Porción:350', 0.9, 'choclo-crudo:800, molida-15-cruda:400, cebolla:300, pechuga-cruda:200, huevo-duro:100, aceitunas:40, pasas:30, leche-entera:200, mantequilla:30, azucar:20, albahaca:5'],
  ['humitas', 'Humitas', 'Unidad:180', 0.95, 'choclo-crudo:1000, cebolla:150, manteca:50, leche-entera:100, albahaca:10'],
  ['empanada-pino', 'Empanada de pino al horno', 'Unidad:220', 0.85, 'harina:500, manteca:100, leche-entera:150, agua:100, molida-20-cruda:500, cebolla:500, huevo-duro:100, aceitunas:50, pasas:30, aceite-maravilla:20'],
  ['empanada-queso', 'Empanada de queso frita', 'Unidad:120', 0.9, 'harina:500, manteca:60, agua:250, queso-gauda:400, aceite-maravilla:150'],
  ['charquican', 'Charquicán', 'Plato:400', 0.9, 'molida-10-cruda:400, papa:800, zapallo:500, choclo-crudo:200, arvejas-crudas:150, cebolla:150, aceite-maravilla:20, agua:300'],
  ['lentejas-guisadas', 'Lentejas guisadas', 'Plato:350', 0.8, 'lentejas-crudas:300, arroz-crudo:80, zanahoria:100, cebolla:100, pimenton-rojo:80, longaniza:100, aceite-maravilla:20, agua:1500'],
  ['garbanzos-guisados', 'Garbanzos guisados', 'Plato:350', 0.8, 'garbanzos-crudos:300, zapallo:200, cebolla:100, aceite-maravilla:20, agua:1200'],
  ['carbonada', 'Carbonada', 'Plato:450', 0.85, 'posta-cruda:400, papa:500, zapallo:300, zanahoria:150, choclo-crudo:150, arvejas-crudas:100, porotos-verdes-crudos:100, arroz-crudo:50, cebolla:100, pimenton-rojo:60, aceite-maravilla:15, agua:1500'],
  ['arroz-graneado', 'Arroz graneado a la chilena', 'Taza:160|Porción:150', 0.9, 'arroz-crudo:300, aceite-maravilla:20, zanahoria:50, ajo:5, agua:600'],
  ['ensalada-chilena', 'Ensalada chilena', 'Plato:150', 1, 'tomate:500, cebolla:150, aceite-maravilla:20, cilantro:5'],
  ['pebre', 'Pebre', 'Cucharada:15|Porción:40', 1, 'tomate:300, cebolla:100, cilantro:30, aji-verde:20, aceite-maravilla:20, ajo:5, vinagre:10'],
  ['ensalada-lechuga', 'Ensalada de lechuga', 'Plato:120', 1, 'lechuga:150, aceite-maravilla:10, jugo-limon:10'],
  ['sopaipilla-prep', 'Sopaipilla', 'Unidad:45', 0.9, 'harina:500, zapallo-cocido:250, manteca:60, agua:50, aceite-maravilla:120'],
  ['marraqueta', 'Marraqueta', 'Unidad:100|Media:50', 0.85, 'harina:1000, agua:600, levadura:20, sal:20, manteca:20'],
  ['hallulla', 'Hallulla', 'Unidad:90', 0.85, 'harina:1000, manteca:150, leche-entera:300, agua:250, levadura:20, sal:20, azucar:20'],
  ['pan-amasado', 'Pan amasado', 'Unidad:100', 0.85, 'harina:1000, manteca:150, agua:500, levadura:20, sal:20'],
  ['completo-italiano', 'Completo italiano', 'Unidad:260', 1, 'pan-completo:80, vienesa:45, palta:60, tomate:50, mayonesa:25'],
  ['completo-simple', 'Completo simple (ketchup y mostaza)', 'Unidad:150', 1, 'pan-completo:80, vienesa:45, ketchup:15, mostaza:10'],
  ['chacarero', 'Chacarero', 'Unidad:360', 1, 'pan-amasado:120, lomo-liso:100, porotos-verdes:60, tomate:50, aji-verde:10, mayonesa:20'],
  ['barros-luco', 'Barros Luco', 'Unidad:240', 1, 'marraqueta:100, lomo-liso:100, queso-gauda:40'],
  ['churrasco-palta', 'Churrasco palta', 'Unidad:260', 1, 'marraqueta:100, lomo-liso:100, palta:60'],
  ['lomito-italiano', 'Lomito italiano', 'Unidad:355', 1, 'pan-amasado:120, pernil:100, palta:60, tomate:50, mayonesa:25'],
  ['choripan', 'Choripán', 'Unidad:200', 1, 'marraqueta:100, chorizo:100'],
  ['pan-palta', 'Pan con palta', 'Unidad:180', 1, 'marraqueta:100, palta:80'],
  ['pan-huevo', 'Pan con huevo revuelto', 'Unidad:220', 1, 'marraqueta:100, huevo-revuelto:120'],
  ['pan-queso-jamon', 'Pan con jamón y queso', 'Unidad:150', 1, 'marraqueta:100, jamon-cerdo:30, queso-gauda:20'],
  ['pollo-arvejado', 'Pollo arvejado', 'Plato:350', 0.85, 'trutro-crudo:600, arvejas-crudas:300, zanahoria:200, cebolla:150, aceite-maravilla:20, agua:300'],
  ['pastel-papas', 'Pastel de papas', 'Porción:350', 0.9, 'papa:1000, leche-entera:150, mantequilla:40, molida-15-cruda:500, cebolla:300, huevo-duro:100, aceitunas:40'],
  ['tallarines-bolonesa', 'Tallarines con salsa boloñesa', 'Plato:400', 0.95, 'fideos:920, molida-10-cruda:400, salsa-pasta:500, cebolla:150, aceite-maravilla:15'],
  ['arroz-pollo', 'Arroz con pollo', 'Plato:400', 0.9, 'arroz-crudo:300, agua:650, pechuga-cruda:400, zanahoria:100, arvejas-crudas:100, pimenton-rojo:60, cebolla:100, aceite-maravilla:20'],
  ['tortilla-acelga', 'Tortilla de acelga', 'Porción:150', 0.9, 'acelga-cocida:300, huevo:250, cebolla:80, aceite-maravilla:15, harina:20'],
  ['tomatican', 'Tomaticán', 'Plato:350', 0.85, 'tomate:600, molida-10-cruda:300, choclo-crudo:200, cebolla:150, aceite-maravilla:15'],
  ['crema-zapallo', 'Crema de zapallo', 'Plato:300', 0.85, 'zapallo:800, papa:200, cebolla:100, leche-entera:200, mantequilla:20, agua:400'],
  ['pantrucas', 'Pantrucas', 'Plato:450', 0.85, 'harina:300, huevo:50, posta-cruda:300, papa:300, zanahoria:100, cebolla:100, agua:1650'],
  ['salpicon', 'Salpicón de pollo', 'Porción:250', 1, 'pechuga-cocida:300, papa-cocida:300, tomate:200, cebolla:80, choclo:100, arvejas:100, mayonesa:50, aceite-maravilla:10'],
  ['palta-reina', 'Palta reina', 'Unidad:230', 1, 'palta:150, pechuga-cocida:60, mayonesa:20'],
  ['ceviche', 'Ceviche de pescado', 'Porción:200', 1, 'merluza-cruda:500, jugo-limon:200, cebolla:150, cilantro:20, pimenton-rojo:50, aji-verde:10'],
  ['chorrillana', 'Chorrillana', 'Porción:400', 1, 'papas-fritas:400, lomo-liso:200, cebolla-cocida:150, huevo-frito:100, aceite-maravilla:20'],
  ['anticucho', 'Anticucho', 'Unidad:250', 0.9, 'posta-cruda:150, longaniza:50, cebolla:30, pimenton-rojo:30, aceite-maravilla:5'],
  ['machas-parmesana', 'Machas a la parmesana', 'Porción:150', 1, 'almejas:200, queso-parmesano:40, mantequilla:10, vino-blanco:20'],
  ['sushi-roll', 'Roll de sushi (salmón, queso crema y palta)', 'Roll (8 cortes):280|Corte:35', 1, 'arroz:180, salmon-crudo:50, queso-crema:30, palta:30, azucar:5, vinagre:10'],
  ['mote-huesillo', 'Mote con huesillo', 'Vaso:350', 1, 'mote-trigo:80, huesillos:60, azucar:30, agua:250'],
  ['leche-asada', 'Leche asada', 'Porción:150', 0.9, 'leche-entera:1000, huevo:300, azucar:200'],
  ['semola-leche', 'Sémola con leche', 'Porción:180', 0.95, 'leche-entera:1000, semola:100, azucar:80'],
  ['calzones-rotos', 'Calzones rotos', 'Unidad:30', 0.9, 'harina:500, huevo:100, mantequilla:50, azucar:100, leche-entera:100, aceite-maravilla:100, azucar-flor:20'],
  ['avena-leche', 'Avena con leche', 'Taza:300', 1, 'avena:50, leche-descremada:250'],
  ['batido-proteina', 'Batido de proteína con leche', 'Vaso:280', 1, 'whey:30, leche-descremada:250'],
];
